---
# copyright Utrecht University

- name: Ensure pip is installed
  package:
    name: python-pip
    state: present


- name: Ensure python-irodsclient is installed
  pip:
    name: python-irodsclient
    state: present


- name: Ensure all resources exist
  become_user: irods
  become: yes
  irods_resource:
    name: "{{ item.name }}"
    resource_type: "{{ item.resource_type }}"
    host: "{{ item.host | default('EMPTY_RESC_HOST') }}"
    vault_path: "{{ item.vault_path | default('EMPTY_RESC_PATH')}}"
    children: "{{ item.children | default([]) }}"
  with_items: "{{ irods_resources }}"


- name: Ensure iRODS default resource is set in core.re
  become_user: '{{ irods_service_account }}'
  become: yes
  lineinfile:
    path: /etc/irods/core.re
    regexp: "^acSetRescSchemeForCreate"
    line: "acSetRescSchemeForCreate {msiSetDefaultResc(\"\
           {{ irods_default_resc }}\",\"null\"); }"


- name: Ensure iRODS default resource is set in irods_environment.json
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_config:
    path: '/var/lib/irods/.irods/irods_environment.json'
    key: 'irods_default_resource'
    value: '{{ irods_default_resc }}'


- name: Ensure iRODS default resource is set in server_config.json
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_config:
    path: '/etc/irods/server_config.json'
    key: 'default_resource_name'
    value: '{{ irods_default_resc }}'
