---
# copyright Utrecht University

- name: Ensure pip is installed
  package:
    name: python-pip
    state: present


- name: Ensure python-irodsclient is installed
  pip:
    name: python-irodsclient
    state: present


- name: Ensure all resources exist
  become_user: irods
  become: yes
  irods_resource:
    name: "{{ item.name }}"
    resource_type: "{{ item.resource_type }}"
    host: "{{ item.host | default('EMPTY_RESC_HOST') }}"
    vault_path: "{{ item.vault_path | default('EMPTY_RESC_PATH')}}"
    children: "{{ item.children | default([]) }}"
  with_items: "{{ irods_resources }}"
