---
- name: Install pip
  yum:
    name: python-pip

- name: Install python-irodsclient
  pip:
    name: python-irodsclient

- name: Ensure all resources exist
  become_user: irods
  become: yes
  irods_resource:
    name: "{{ item.name }}"
    resource_type: "{{ item.resource_type }}"
    host: "{{ item.host | default('EMPTY_RESC_HOST') }}"
    vault_path: "{{ item.vault_path | default('EMPTY_RESC_PATH')}}"
    children: "{{ item.children | default([]) }}"
  with_items: "{{ irods_resources }}"

