---
# copyright Utrecht University
# This playbook deploys a complete Yoda instance.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.5', '>=')"
        msg: >
          "You must update Ansible to at least 2.5 to deploy Yoda."


- name: Add hosts entries to development instances
  hosts: development
  become: yes
  roles:
    - hostentries


- name: Provision portal server
  hosts: portals
  become: yes
  roles:
    - common
    - certificates
    - apache
    - php
    - yoda-portal
    - irods-icommands
    - irods-runtime
    - yoda-davrods
  tags:
    - portal


- name: Provision database server
  hosts: databases
  become: yes
  roles:
    - common
    - postgresql
    - irods-database
  tags:
    - database


- name: Provision iCAT server
  hosts: icats
  become: yes
  roles:
    - common
    - certificates
    - irods-icat
    - irods-runtime
    - irods-microservices
    - composable-resources
  tags:
    - icat


- name: Provision resource server
  hosts: resources
  become: yes
  roles:
    - common
    - certificates
    - irods-resource
    - irods-runtime
    - irods-microservices
  tags:
    - resource


- name: Provision rulesets on iCAT server
  hosts: icats
  become: yes
  roles:
    - role: yoda-rulesets
      install_rulesets: yes
  tags:
    - icat


- name: Provision rulesets on resource server
  hosts: resources
  become: yes
  roles:
    - role: yoda-rulesets
      install_rulesets: no
  tags:
    - resource


- name: Provision public server
  hosts: publics
  become: yes
  roles:
    - common
    - certificates
    - apache
    - yoda-moai
    - yoda-landingpages
    - yoda-public
  tags:
    - public


- name: Provision external user service server
  hosts: eus
  become: yes
  roles:
    - common
    - certificates
    - apache
    - php
    - yoda-external-user-service
  tags:
    - eus
