---
# copyright Utrecht University
# This playbook deploys a complete Yoda instance.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7 to deploy Yoda."

    - name: Verify Yoda Ansible repository is on correct branch
      local_action:
        module: shell
        _raw_params: git branch | grep \* | cut -d ' ' -f2
      changed_when: False
      register: git_branch

    - fail:
        msg: "Make sure your yoda-ansible repository is on branch {{ yoda_version}}. (git checkout {{ yoda_version }})"
      when: yoda_version not in git_branch.stdout and yoda_environment != "development"


- name: Add hosts entries to development instances
  hosts: development
  become: yes
  roles:
    - hostentries


- name: Provision portal server
  hosts: portals
  become: yes
  roles:
    - common
    - certificates
    - { role: acme_certificates, when: yoda_environment == "testing" }
    - apache
    - php
    - yoda-portal
    - irods-icommands
    - irods-runtime
    - yoda-davrods
  tags:
    - portal


- name: Provision database server
  hosts: databases
  become: yes
  roles:
    - common
    - certificates
    - postgresql
    - irods-database
  tags:
    - database


- name: Provision iCAT server
  hosts: icats
  become: yes
  roles:
    - common
    - certificates
    - irods-icat
    - irods-runtime
    - irods-microservices
    - composable-resources
  tags:
    - icat


- name: Provision resource server
  hosts: resources
  become: yes
  roles:
    - common
    - certificates
    - irods-resource
    - irods-runtime
    - irods-microservices
  tags:
    - resource


- name: Provision rulesets on iCAT server
  hosts: icats
  become: yes
  roles:
    - role: yoda-rulesets
      install_rulesets: yes
  tags:
    - icat


- name: Provision rulesets on resource server
  hosts: resources
  become: yes
  roles:
    - role: yoda-rulesets
      install_rulesets: no
  tags:
    - resource


- name: Provision public server
  hosts: publics
  become: yes
  roles:
    - common
    - certificates
    - apache
    - yoda-moai
    - yoda-landingpages
    - yoda-public
  tags:
    - public


- name: Provision external user service server
  hosts: eus
  become: yes
  roles:
    - common
    - certificates
    - apache
    - php
    - yoda-external-user-service
  tags:
    - eus
