---
# This playbook deploys the whole application stack in this site.

- name: Provision portal server
  hosts: portals
  become: yes
  roles:
    - apache
    - php
    - yoda-portal
    - irods-icommands
    - irods-runtime
    - yoda-davrods


- name: Provision database server
  hosts: databases
  become: yes
  roles:
    - irods-database


- name: Provision iCAT server
  hosts: icats
  become: yes
  roles:
    - irods-icat
    - irods-runtime
    - irods-microservices
    - yoda-rulesets


- name: Provision resource server
  hosts: resources
  become: yes
  roles:
    - irods-resource
    - irods-runtime
    - irods-microservices


- name: Add hosts entries to development instances
  hosts: development
  become: yes
  roles:
    - hostentries
