---
# copyright Utrecht University
# This playbook deploys the whole application stack in this site.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full | version_compare('2.3', '>=')"
        msg: >
          "You must update Ansible to at least 2.3 to deploy YoDa."


- name: Add hosts entries to development instances
  hosts: development
  become: yes
  roles:
    - hostentries


- name: Provision portal server
  hosts: portals
  become: yes
  roles:
    - apache
    - php
    - yoda-portal
    - irods-icommands
    - irods-runtime
    - yoda-davrods


- name: Provision database server
  hosts: databases
  become: yes
  roles:
    - postgresql
    - irods-database


- name: Provision iCAT server
  hosts: icats
  become: yes
  roles:
    - irods-icat
    - irods-runtime
    - irods-microservices
    - yoda-rulesets
    - composable-resources


- name: Provision resource server
  hosts: resources
  become: yes
  roles:
    - irods-resource
    - irods-runtime
    - irods-microservices
    - yoda-rulesets

