---
# copyright Utrecht University
# This playbook provisions Yoda instance with the Zabbix agent, PostgreSQL monitoring and Zabbix user access to the database.

- hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version('2.7', '>=')"
        msg: >
          "You must update Ansible to at least 2.7 to deploy Yoda."


- hosts: all
  pre_tasks:
    - name: Verify Yoda Ansible repository is on correct branch
      shell: git branch | grep \* | cut -d ' ' -f2
      register: git_branch
      changed_when: False
      delegate_to: localhost

    - fail:
        msg: "Make sure your yoda-ansible repository is on branch {{ yoda_version}}. (git checkout {{ yoda_version }})"
      when: yoda_version not in git_branch.stdout and yoda_environment != "development"


- name: provision public server with Zabbix
  hosts: publics
  become: yes
  roles:
    - yoda-zabbix-system
  tags:
    - public
