---
# copyright Utrecht University
# This playbook provisions Yoda instance with the Zabbix agent, postgresql monitoring and zabbix user access to the database.

- hosts: all
  pre_tasks:
    - name: Verify Ansible version meets requirements
      assert:
        that: "ansible_version.full is version_compare('2.4', '>=')"
        msg: >
          "You must update Ansible to at least 2.4 to deploy Yoda."

- name: Add hosts entries to development instances
  hosts: development
  become: yes
  roles:
    - hostentries

- name: Provision portal server with Zabbix agent
  hosts: portals
  become: yes
  roles:
   - yoda-zabbixagent
  tags:
    - portal
 
- name: Provision instance with Zabbix agent and postgresql monitoring
  hosts: icats
  become: yes
  roles:
    - yoda-zabbixagent  
    - yoda-zabbixyodaitems
  tags:
    - zabbix

- name: Provision instance with Zabbix agent and postgresqlmonitoring
  hosts: databases
  become: yes
  roles:
    - yoda-zabbixagent
    - yoda-zabbixdatabase
  tags:
    - database

- name: Provision resource server with Zabbix agent
  hosts: resources
  become: yes
  roles:
    - yoda-zabbixagent
  tags:
    - resource


- name: Provision public server with Zabbix agent
  hosts: publics
  become: yes
  roles:
    - yoda-zabbixagent
  tags:
    - 