---
# copyright Utrecht University
# This playbook provisions Yoda instance with the Zabbix agent.

- name: Provision instance with Zabbix agent
  hosts: icats
  become: yes
  roles:
    - yoda-zabbix
  tags:
    - zabbix