---
# copyright Utrecht University

yoda_deployment_user: yodadeployment

yoda_version: development
irods_php_version: master
codeigniter_version: 2.2-uu

portal_server_name: portal.yoda.dev
update_portal: yes

yoda_php_encryption_key: dummy

# iRODS configuration.
irods_default_resource: demoResc
irods_auth_type: STANDARD
irods_zone: tempZone
irods_icat_fqdn: icat.yoda.dev
