---
# copyright Utrecht University

########################
# Ansible configuration
########################
ansible_user: admincentos                          # Administrative user on instance for Ansible

surfadmin: surfadmin
surfpass: useTheForce

#Slight YODA customization instantly, relative to top of GIT repo.
CUSTOMIZE: True
FAVICONPATH: environments/surf/files/surfsara_favicon.png
HEADERIMG: environments/surf/files/surfsara_header.png
FOOTERIMG: environments/surf/files/surfsara_footer.png
SPLASHIMG: environments/surf/files/splash.png
IMGURLDIRECT: https://www.surfsara.nl
LOGINPLACEHOLDER: player.two@surfsara.nl
PORTALTABTEXT: SURFsara Yoda
PUBLICTABTEXT: SURFsara Data Publication Platform

# Allows root from portal to reach ext for PG dumps for backup
root_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpgIBAAKCAQEAvq5Kbpa+srQ2+DkS49cV3Eidyw0HHAMiuSXuhoFM967BwW++
  HcWr2tc19L7JY2R+ob9Yu23ZmojHpi4TI+7IMbrH/hnN06xgWXrsr+tKLBqX4OuA
  6CcsSg/Z9XIlckzE6quwcYzLMjnzBf3eQ0M2TKlMeEtOZhQSCWyxVk/fAQ2hdJvh
  Gz+e1/B/9cqDqTkEEr5utNF1MF4aeCaErgAUMEoezim6BcqMG+t75YRDknPLMvZp
  OwZQHD6PjC684QjZ9N3me95SEDWNfVpL7cq3CT57QgWU3vbCdef4JXnO9i90UY+i
  Q6b4YTIa/NklGGeKX9CwyFZ44eYR6u8jC+b+3QIDAQABAoIBAQCqVOkadsBsxD1i
  aSFts+HMQHXsP3v9UvO+rpqvPmuxyUM9d4M99yk4OQzyz0b46XmRJWuvKka7G7o0
  wW3JqHDes3oZi5Voo9ABvqQV1boRQcQwYE9rkiqnEhfigI/g1aEF/E6GcH3HJSrp
  TEkyjqS/wHAV+TdUSlN+ZcDYWEreFXNFW+16IjONeI3gS3GreqfLd4tYpFGmAyVR
  WrXDWNd/oQ/1WGMYoOkNExTRP2+31yAa03BFMH4rwAdYb3H3T84aSpsncB9Fv426
  fjIoN+L+skGb0aUGrgDKwKOfI/vLHnxCXYgKklNDOih7DXrhjKiyW0qkxrIz61Yy
  CBmsj10FAoGBAN+4mpMZ+5P85CmIRIxW01GmCiLB21nuZvMr50GulE15CMqskpr3
  lcSNdwJOafGhadYeh2x4oKpq0P+mh4sW3pN0KNNubHUcmSIvuppoCTkJBYl4ZlbU
  YGuaHTpwyt+4JGtL7cYdfF5KEgW/Ehl3KF7qJSh1DLboTgsj4/YT/XpfAoGBANox
  TliriZJ48DkXTEeRhbj5gRveZJXag2uMEruADxlAW/Ttkt50i0amL5XisxlYzHUv
  6iBh28zYt5pUJJa1Hp2VVvf5wcl5uQvQIKnfX3cJZ4J569ne98lJ2bZJOOBjJ4A4
  56c+7+EsS/348dENDYB2p2wKmvzp+vvRSbeuYwhDAoGBALmAc0MH5091AKbjY5tO
  HxhzabIaNcxi3iBBxhXzMOrwMfcDkuhF5Hw+pHBYHoaJRZ2SYM3zU50axsNEDN2q
  j9GKHpP52ppcpSjwlHSVURhmv52WJJ1Yqb5u4k9j2QQZxrDlG3oLVuVD25/CJ7rP
  z7yrvzXFoE5FXvjjwJB5UNNXAoGBANRiChDlaBPbBHmN5AIF9FQJCVNHNkFnYWTe
  A53fGNNLgjb2yW8fojIysT8EW7DgbqPi79J1bq4GhTEDllncEuDw7KaTxb2HbkfB
  Xwn7E8GatdabNqfsEOUtrW1x+Jrx6RE2UsbIzFYx+AZOu5LxUaMp2+2epR5p4pQb
  M9ZHOL5hAoGBAMLsq/38QgKpvM4qra1KrlEW12djgSOCsoMvDW/yrBOShjBJLucj
  Gsi2ilB7tqtKewDJS1ev9ztr+eV+cbFYo6iu6sNof36Nerlp9E6uSwFU5QEMvwZQ
  2WF+ihmP5Zm2S2exJYpU8tgKdtHJWatgJRG4EN3KeRNyqnM6dHDC+r+4
  -----END RSA PRIVATE KEY-----

root_crt: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+rkpulr6ytDb4ORLj1xXcSJ3LDQccAyK5Je6GgUz3rsHBb74dxava1zX0vsljZH6hv1i7bdmaiMemLhMj7sgxusf+Gc3TrGBZeuyv60osGpfg64DoJyxKD9n1ciVyTMTqq7BxjMsyOfMF/d5DQzZMqUx4S05mFBIJbLFWT98BDaF0m+EbP57X8H/1yoOpOQQSvm600XUwXhp4JoSuABQwSh7OKboFyowb63vlhEOSc8sy9mk7BlAcPo+MLrzhCNn03eZ73lIQNY19WkvtyrcJPntCBZTe9sJ15/glec72L3RRj6JDpvhhMhr82SUYZ4pf0LDIVnjh5hHq7yML5v7d root@portal1.irodspoc-sara.surf-hosted.nl


#####################
# Yoda configuration
#####################
instance: full                                     # Name of Yoda instance, as defined in hosts file
yoda_version: release-1.5                          # Git branch, for example: development or release-1.4
yoda_environment: production                       # Yoda environment: development, testing, acceptance or production
yoda_portal_fqdn:  3-yoda.irodspoc-sara.surf-hosted.nl                # Yoda Portal fully qualified domain name (FQDN)
yoda_davrods_fqdn: 3-data.irodspoc-sara.surf-hosted.nl                  # Yoda Davrods WebDAV fully qualified domain name (FQDN)
yoda_davrods_anonymous_fqdn: 3-data.irodspoc-sara.surf-hosted.nl # Yoda Davrods anonymous WebDAV fully qualified domain name (FQDN)
yoda_davrods_anonymous_port: 8443                  


######################
# Yoda Portal modules
######################
modules:
  - name: group-manager
    repo: "https://github.com/UtrechtUniversity/yoda-portal-group-manager.git"
    dest: /var/www/yoda/yoda-portal/modules/group-manager
    version: "{{ yoda_version }}"
  - name: research
    repo: "https://github.com/UtrechtUniversity/yoda-portal-research.git"
    dest: /var/www/yoda/yoda-portal/modules/research
    version: "{{ yoda_version }}"
  - name: statistics
    repo: "https://github.com/UtrechtUniversity/yoda-portal-statistics.git"
    dest: /var/www/yoda/yoda-portal/modules/statistics
    version: "{{ yoda_version }}"
  - name: vault
    repo: "https://github.com/UtrechtUniversity/yoda-portal-vault.git"
    dest: /var/www/yoda/yoda-portal/modules/vault
    version: "{{ yoda_version }}"

######################
# iRODS configuration
######################
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_database_user: irodsdb               # The iRODS database username
irods_database_password: irodsdev          # The password for the iRODS database username
irods_zone: tempZone                       # The name of the iRODS Zone
irods_icat_fqdn: 3-yoda.irodspoc-sara.surf-hosted.nl             # iRODS iCAT fully qualified domain name (FQDN)
irods_database_fqdn: 3-yoda.irodspoc-sara.surf-hosted.nl    # iRODS database fully qualified domain name (FQDN)
irods_resource_fqdn: 3-yoda.irodspoc-sara.surf-hosted.nl    # iRODS resource fully qualified domain name (FQDN)
irods_default_resc: irodsResc              # iRODS default resource name
irods_ssl_verify_server: none              # Verify TLS certificate, use 'cert' for acceptance and production
irods_resources:
  - name: dev001_1
    host: "{{ irods_icat_fqdn }}"
    vault_path: /data/Vault1_1
    resource_type: unixfilesystem

  - name: dev001_2
    resource_type: unixfilesystem
    host: "{{ irods_icat_fqdn }}"
    vault_path: /data/Vault1_2

  - name: dev001_p1
    resource_type: passthru
    children:
      - dev001_1

  - name: dev001_p2
    resource_type: passthru
    children:
      - dev001_2

  - name: dev001
    resource_type: random
    children:
      - dev001_p1
      - dev001_p2

  - name: irodsResc
    resource_type: random
    children:
      - dev001

  - name: dev002_1
    resource_type: unixfilesystem
    host: "{{ irods_resource_fqdn }}"
    vault_path: /data/Vault2_1

  - name: dev002_p1
    resource_type: passthru
    children:
      - dev002_1

  - name: dev002
    resource_type: random
    children:
      - dev002_p1

  - name: irodsRescRepl
    resource_type: random
    children:
      - dev002

########################
# Ruleset configuration
########################
rulesets:
  - name: irods-ruleset-youth-cohort
    repo: https://github.com/UtrechtUniversity/irods-ruleset-youth-cohort.git
    ruleset_name: rules-yc
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: irods-ruleset-research
    repo: https://github.com/UtrechtUniversity/irods-ruleset-research.git
    ruleset_name: rules-research
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: irods-ruleset-uu
    repo: https://github.com/UtrechtUniversity/irods-ruleset-uu.git
    ruleset_name: rules-uu
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: core
    ruleset_name: core
    path: /etc/irods/core.re
    install_scripts: no

################################
# Research module configuration
################################
default_yoda_schema: default-0   # Default Yoda XML scheme: default or test
enable_revisions: 1            # Enable revisions: yes (1) or no (0)
revision_strategy: B           # Revision strategy: A, B, J or Simple
yoda_random_id_length: 6       # Length of random ID to add to persistent identifier
yoda_prefix: UU01              # Prefix for internal portion of persistent identifier
update_rulesets: yes           # Update already installed rulesets with git
update_schemas: 1              # Update already installed schemas, formelements and stylesheets: yes (1) or no (0)
credential_files: PLACEHOLDER  # Location of Yoda credentials files

#####################
# Mail notifications
#####################
send_notifications: 0               # Enable notifications: yes (1) or no (0)
notifications_sender_email: noreply@3-public.irodspoc-sara.surf-hosted.nl # Notifiations sender email address
notifications_reply_to: noreply@3-public.irodspoc-sara.surf-hosted.nl     # Notifiations Reply-To email address
smtp_server: mta.surfsara.nl            # SMTP server to send mail to
smtp_username: yodaMailer          # SMTP server username
smtp_password: seeSaumWithQuestions          # SMTP server password

#########################
# DataCite Configuration
#########################
datacite_server: mds.test.datacite.org  # DataCite server URI
datacite_username: PLACEHOLDER          # DataCite username
datacite_password: PLACEHOLDER          # DataCite password
datacite_prefix: 10.5072                # DataCite DOI prefix

#########################
# EPIC PID Configuration
#########################
epic_url: PLACEHOLDER              # EPIC PID server URI (undefined disables EPIC PID)
epic_handle_prefix: PLACEHOLDER    # EPIC PID prefix

###########################
# PAM Radius configuration
###########################
# server, shared secret, timeout (s)
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

#######################
# Zabbix configuration
#######################
zabbix_server: PLACEHOLDER

############################
# Public host configuration
############################
yoda_public_host: 3-public.irodspoc-sara.surf-hosted.nl     # Yoda public host
yoda_public_fqdn: 3-public.irodspoc-sara.surf-hosted.nl     # Yoda public fully qualified domain name (FQDN)

# Yoda public upload private key (base64 encoded)
# ssh-keygen -t ed25519 -> base64
upload_priv_key: |
  LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFB
  QUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhP
  UUFBQUNDTGlhY01DT2xPZzNpSFg4VXdYOHpWUk11cFB2Y2NyTTdmQUNodU9WMi80UUFBQUpoQTVj
  YTlRT1hHCnZRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ0xpYWNNQ09sT2czaUhYOFV3WDh6VlJN
  dXBQdmNjck03ZkFDaHVPVjIvNFEKQUFBRUFtRng0MmVDSDBYOHFHaXpmUmFpcFJWa3MzcVo1OWda
  SU92TUJkZy85SnhZdUpwd3dJNlU2RGVJZGZ4VEJmek5WRQp5NmsrOXh5c3p0OEFLRzQ1WGIvaEFB
  QUFEbWx5YjJSelFHTnZiV0pwYm1Wa0FRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZB
  VEUgS0VZLS0tLS0K

# Yoda public upload public key (base64 encoded)
upload_pub_key: |
  c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUl1SnB3d0k2VTZEZUlkZnhUQmZ6
  TlZFeTZrKzl4eXN6dDhBS0c0NVhiL2ggaXJvZHNAY29tYmluZWQK

######################################
# External user service configuration
######################################
yoda_eus_fqdn: 3-ext.irodspoc-sara.surf-hosted.nl
eus_api_fqdn: 3-ext.irodspoc-sara.surf-hosted.nl
eus_api_secret: saltyPretzels
eus_db_password: testPasswordGoeshere
eus_smtp_host: 127.0.0.1
eus_smtp_port: 25
eus_smtp_auth: false
eus_smtp_security: "''"
eus_smtp_user: ""
eus_smtp_password: ""
eus_smtp_from_address: noreply@3-ext.irodspoc-sara.surf-hosted.nl 
eus_smtp_replyto_address: noreply@3-ext.irodspoc-sara.surf-hosted.nl
eus_mail_template: surf
