---
# copyright Utrecht University

- name: Ensure yodadeployment user exists
  user:
    name: "{{ yoda_deployment_user }}"


- name: Ensure yodadeployment has access to /var/www/yoda
  file:
    path: /var/www/yoda
    state: directory
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: 0755


- name: Checkout YoDa portal source
  become_user: "{{ yoda_deployment_user }}"
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    update: "{{ update_portal }}"
  with_items: "{{ portal_sources }}"


- name: Link public directories of YoDa portal
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - src: '{{ yoda_public_dir }}'
      dest: /var/www/yoda/public
    - src: '{{ yoda_public_dir }}'
      dest: /var/www/html/public


- name: Checkout YoDa modules
  become_user: "{{ yoda_deployment_user }}"
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    update: "{{ update_portal }}"
  with_items: "{{ modules }}"


- name: Link public directories of YoDa modules
  file:
    src: '{{ item.dest }}/public'
    dest: '{{ yoda_public_dir }}/{{ item.name }}'
    state: link
  with_items: "{{ modules }}"


- name: Generate php session encryption key
  command: openssl rand -base64 32
    creates=/var/www/yoda/yoda-portal/config/config_local.php
  register: random_key
  when: not ansible_check_mode


- name: Store encryption key in variable
  set_fact:
    yoda_php_encryption_key: '{{ random_key.stdout }}'
  when: not ansible_check_mode


- name: Create config_local.php
  template:
    src: config_local.php.j2
    dest: /var/www/yoda/yoda-portal/config/config_local.php
    owner: "{{ yoda_deployment_user }}"
    mode: 0644
    force: no


- name: Create .htaccess
  command: cp /var/www/yoda/yoda-portal/public/.htaccess.template-{{ codeigniter_environment }}
    /var/www/yoda/yoda-portal/public/.htaccess
    creates=/var/www/yoda/yoda-portal/public/.htaccess


- name: Ensure YoDa home is executable
  file:
    path: /var/www/yoda
    mode: 0755


- name: Copy YoDa Portal virtual host config for Apache
  template:
    src: "yoda-portal-vhost.conf.j2"
    dest: "/etc/httpd/conf.d/yoda-portal-vhost.conf"
  notify: Restart Apache webserver
