---
# copyright Utrecht University

- name: Ensure yodadeployment user exists
  user:
    name: "{{ yoda_deployment_user }}"
    home: /var/www/yoda


- name: Checkout YoDa sources
  become_user: "{{ yoda_deployment_user }}"
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    update: "{{ update_portal }}"
  with_items: "{{ portal_sources }}"


- name: Link portal public directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - src: /var/www/yoda/yoda-portal/public
      dest: /var/www/yoda/public
    - src: /var/www/yoda/yoda-portal/modules/group-manager/public
      dest: /var/www/yoda/yoda-portal/public/group-manager
    - src: /var/www/yoda/yoda-portal/modules/research/public
      dest: /var/www/yoda/yoda-portal/public/research
    - src: /var/www/yoda/yoda-portal/modules/statistics/public
      dest: /var/www/yoda/yoda-portal/public/statistics
    - src: /var/www/yoda/yoda-portal/public
      dest: /var/www/html/public


- name: Generate php session encryption key
  command: openssl rand -base64 32
    creates=/var/www/yoda/yoda-portal/config/config_local.php
  register: random_key


- name: Store encryption key in variable
  set_fact:
    yoda_php_encryption_key: '{{ random_key.stdout }}'


- name: Create config_local.php
  template:
    src: config_local.php.j2
    dest: /var/www/yoda/yoda-portal/config/config_local.php
    owner: "{{ yoda_deployment_user }}"
    mode: 0644
    force: no


- name: Create .htaccess
  command: cp /var/www/yoda/yoda-portal/public/.htaccess.template
    /var/www/yoda/yoda-portal/public/.htaccess
    creates=/var/www/yoda/yoda-portal/public/.htaccess


- name: Ensure YoDa home is executable
  file:
    path: /var/www/yoda
    mode: 0755


- name: Copy YoDa Portal config for Apache
  template:
    src: "yoda-portal.conf.j2"
    dest: "/etc/httpd/conf.d/yoda-portal.conf"
  notify: Restart Apache webserver
