---
# copyright Utrecht University


- name: Ensure yoda_irodscommon.userparams.conf exists
  stat: path=/etc/zabbix/yoda-zabbix/zabbix-irodscommon/yoda_irodscommon.userparams.conf
  register: irodscommon_zabbix_agentd


- name: Copy yoda_irodscommon.userparams.conf to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/yoda_irodscommon.userparams.conf /etc/zabbix/zabbix_agentd.d/yoda_irodscommon.userparams.conf
  when: not irodscommon_zabbix_agentd.stat.exists or yoda-zabbix_repo.changed


- name: Ensure right file ownership on yoda_irodscommon.userparams.conf
  file:
    path: /etc/zabbix/zabbix_agentd.d/yoda_irodscommon.userparams.conf
    owner: zabbix
    group: zabbix
    mode: 0400


- name: Ensure yoda-zabbix-irodscommon-sudoers exists
  stat: path=/etc/sudoers.d/yoda-zabbix-irodscommon-sudoers
  register: irodscommon_zabbix_sudoers


- name: Copy yoda-zabbix-irodscommon.sudoers to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/yoda-zabbix-irodscommon-sudoers /etc/sudoers.d/yoda-zabbix-irodscommon-sudoers
  when: not irodscommon_zabbix_sudoers.stat.exists or yoda_zabbix_repo.changed


- name: Ensure right file ownership on yoda-zabbix-irodscommon-sudoers
  file:
    path: /etc/sudoers.d/yoda-zabbix-irodscommon-sudoers
    owner: root
    group: root
    mode: 0440


- name: Copy Yoda Zabbix rules
  shell: "cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/*.r /etc/zabbix/zabbix_agentd.d/"
  when: yoda_zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Copy Yoda Zabbix scripts
  shell: "cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/*.sh /etc/zabbix/zabbix_agentd.d/"
  when: yoda_zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Find Yoda Zabbix rules
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.r"
  register: irodscommon_zabbix_rules


- name: Ensure right file ownership on Yoda Zabbix rules
  file:
    path: "{{ item.path }}"
    owner: irods
    group: irods
    mode: 0500
  with_items: "{{ irodscommon_zabbix_rules.files }}"


- name: Find Yoda Zabbix scripts
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.sh"
  register: irodscommon_zabbix_scripts


- name: Ensure right file ownership on Yoda Zabbix scripts
  file:
    path: "{{ item.path }}"
    owner: zabbix
    group: zabbix
    mode: 0500
  with_items: "{{ irodscommon_zabbix_scripts.files }}"

