---
# copyright Utrecht University


- name: Copy yoda_irodscommon.userparams.conf to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/yoda_irodscommon.userparams.conf /etc/zabbix/zabbix_agentd.d/yoda_irodscommon.userparams.conf


- name: Ensure right file ownership on yoda_irodscommon.userparams.conf
  file:
    path: /etc/zabbix/zabbix_agentd.d/yoda_irodscommon.userparams.conf
    owner: zabbix
    group: zabbix
    mode: 0400


- name: Copy yoda-zabbix-irodscommon.sudoers to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/yoda-zabbix-irodscommon-sudoers /etc/sudoers.d/yoda-zabbix-irodscommon-sudoers


- name: Ensure right file ownership on yoda-zabbix-irodscommon-sudoers
  file:
    path: /etc/sudoers.d/yoda-zabbix-irodscommon-sudoers
    owner: root
    group: root
    mode: 0440


- name: Copy Yoda Zabbix scripts
  shell: "cp /etc/zabbix/yoda-zabbix/zabbix-irodscommon/*.sh /etc/zabbix/zabbix_agentd.d/"
  notify: Restart Zabbix agent


- name: Find Yoda Zabbix scripts
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.sh"
  register: irodscommon_zabbix_scripts


- name: Ensure right file ownership on Yoda Zabbix scripts
  file:
    path: "{{ item.path }}"
    owner: zabbix
    group: zabbix
    mode: 0500
  with_items: "{{ irodscommon_zabbix_scripts.files }}"

