---
# copyright Utrecht University

- name: Check if iRODS microservices are installable from repository
  yum:
    list: "{{ item.value.package }}"
  with_dict: "{{ microservices }}"
  register: irods_microservices_repo


- name: Download iRODS microservice packages
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ rpm_dest_dir }}/{{ item.value.filename }}"
    checksum: "{{ item.value.checksum }}"
  with_dict: "{{ microservices }}"
  when: not irods_microservices_repo.results


- name: Install iRODS microservice packages from downloaded rpm
  yum:
    name: "{{ rpm_dest_dir }}/{{ item.value.filename }}"
    state: present
  with_dict: "{{ microservices }}"
  when: not irods_microservices_repo.results


- name: Ensure microservice packages from downloaded rpm
  yum:
    name: "{{ item.value.package }}"
    state: present
  with_dict: "{{ microservices }}"
  when: irods_microservices_repo.results


- name: Undo the ownership modifications by the sudo microservices
  file:
    path: "{{ item }}"
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: 0755
  with_items:
    - /etc/irods
    - /var/lib/irods
    - /var/lib/irods/plugins
    - /var/lib/irods/plugins/microservices
