---
# copyright Utrecht University

- name: Remove old json and xml microservice packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - rit-irods-microservices
    - irods-microservice-plugins-loadmeta


- name: Check if iRODS microservices are installable from repository
  yum:
    list: "{{ item.value.package }}"
  with_dict: "{{ microservices }}"
  register: irods_microservices_repo


- name: Download iRODS microservice packages
  get_url:
    url: "{{ item.item.value.url }}"
    dest: "{{ rpm_dest_dir }}/{{ item.item.value.filename }}"
    checksum: "{{ item.item.value.checksum }}"
  when: not item.results
  with_items: "{{ irods_microservices_repo.results }}"


- name: Install iRODS microservice packages from downloaded rpm
  yum:
    name: "{{ rpm_dest_dir }}/{{ item.item.value.filename }}"
    state: present
  when: not item.results
  with_items: "{{ irods_microservices_repo.results }}"


- name: Ensure microservice packages from downloaded rpm
  yum:
    name: "{{ item.item.value.package }}"
    state: present
  when: not item.results
  with_items: "{{ irods_microservices_repo.results }}"


- name: Ensure available microservices are installed from repository
  package:
    name: "{{ item.value.package }}"
    state: present
  with_dict: "{{ microservices }}"


- name: Undo the ownership modifications by the microservices installation
  file:
    path: "{{ item.directory }}"
    recurse: "{{ item.recursive }}"
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
  with_items:
    - { directory: '/var/lib/irods', recursive: 'no' }
    - { directory: '/var/lib/irods/plugins', recursive: 'yes' }
