---
- name: Checkout rulesets from github
  become_user: irods
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/irods/{{ item.name }}"
    version: "{{ item.version }}"
    update: "{{ update_rulesets }}"
  with_items: "{{ rulesets }}"

- name: Run make install for each ruleset
  become_user: irods
  become: yes
  shell: make install
  args:
    chdir: "/etc/irods/{{ item.name }}"
    creates: "/etc/irods/{{ item.ruleset_name }}.re"
  with_items: "{{ rulesets }}"

