---
# copyright Utrecht University

- name: Checkout rulesets from github
  become_user: irods
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/irods/{{ item.name }}"
    version: "{{ item.version }}"
    update: "{{ update_rulesets }}"
  with_items: "{{ rulesets }}"
  register: repochanges


- name: Run make install for each ruleset
  become_user: irods
  become: yes
  shell: make install
  args:
    chdir: "/etc/irods/{{ item.0.name }}"
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"

