---
# copyright Utrecht University

- name: Ensure Python dependencies are installed
  package:
    name:
      - python-enum34
      - python-lxml
      - python-pip
    state: present


- name: Install Python JSON to AVU module
  pip:
    name: git+https://github.com/MaastrichtUniversity/irods_avu_json.git


- name: Checkout rulesets from github
  become_user: "{{ irods_service_account }}"
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/irods/{{ item.name }}"
    version: "{{ item.version }}"
    update: "{{ update_rulesets }}"
  with_items: "{{ rulesets }}"
  when: "'repo' in item"
  register: repochanges


- name: Remove temporary rule files left behind
  become_user: "{{ irods_service_account }}"
  become: yes
  command:
    /bin/rm -f /etc/irods/*.re.*
  ignore_errors: true


- name: Run make install for each ruleset
  become_user: "{{ irods_service_account }}"
  become: yes
  make:
    chdir: "/etc/irods/{{ item.0.name }}"
    target: install
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"


- name: Ensure all rulesets are in server config
  become_user: "{{ irods_service_account }}"
  become: yes
  irods_rulesets:
    config_path: "/etc/irods/server_config.json"
    rulesets: "{{ rulesets | map(attribute='ruleset_name') | list  }}"
  when: not ansible_check_mode


- include_tasks: "{{ ruleset.name }}.yml"
  with_items: "{{ rulesets }}"
  loop_control:
    loop_var: ruleset
  when: ruleset.install_scripts and install_rulesets
