---
# copyright Utrecht University

- name: Checkout rulesets from github
  become_user: irods
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/etc/irods/{{ item.name }}"
    version: "{{ item.version }}"
    update: "{{ update_rulesets }}"
  with_items: "{{ rulesets }}"
  register: repochanges


- name: Run make install for each ruleset
  become_user: irods
  become: yes
  shell: make install
  args:
    chdir: "/etc/irods/{{ item.0.name }}"
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"


- name: Copy script to add rulesets to server config
  template:
    src: configure_rulesets.py.j2
    dest: /home/{{ ansible_ssh_user }}/configure_rulesets.py
    mode: a+x


- name: Reset server config rulesets
  shell:
    /home/{{ ansible_ssh_user }}/configure_rulesets.py /etc/irods/server_config.json 0 1
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"


- name: Add rulesets to server config
  shell:
    /home/{{ ansible_ssh_user }}/configure_rulesets.py /etc/irods/server_config.json {{ item.0.ruleset_name }}
  when: item.1.changed
  with_together:
    - "{{ rulesets }}"
    - "{{ repochanges.results }}"
