---
# copyright Utrecht University


- name: Copy yoda_portal.userparams.conf to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-portal/yoda_portal.userparams.conf /etc/zabbix/zabbix_agentd.d/yoda_portal.userparams.conf


- name: Ensure right file ownership on yoda_portal.userparams.conf
  file:
    path: /etc/zabbix/zabbix_agentd.d/yoda_portal.userparams.conf
    owner: zabbix
    group: zabbix
    mode: 0400


- name: Copy yoda-zabbix-portal-sudoers to right place
  command: cp /etc/zabbix/yoda-zabbix/zabbix-portal/yoda-zabbix-portal-sudoers /etc/sudoers.d/yoda-zabbix-portal-sudoers


- name: Ensure right file ownership on zabbix_agentd.userparams.conf
  file:
    path: /etc/sudoers.d/yoda-zabbix-portal-sudoers
    owner: root
    group: root
    mode: 0440


- name: Copy Yoda zabbix scripts
  shell: "cp /etc/zabbix/yoda-zabbix/zabbix-portal/*.sh /etc/zabbix/zabbix_agentd.d/"
  notify: Restart Zabbix agent


- name: Find Yoda Zabbix scripts
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.sh"
  register: zabbix-portal-scripts


- name: Ensure right file ownership on Yoda Zabbix scripts
  file:
    path: "{{ item.path }}"
    owner: zabbix
    group: zabbix
    mode: 0500
  with_items: "{{ zabbix-portal-scripts.files }}"

