---
# copyright Utrecht University

- name: Create zabbix database user
  become_user: postgres
  become: yes
  postgresql_user:
    db: "{{ zabbix_database_name }}"
    name: "{{ zabbix_database_user }}"
    priv: "CONNECT"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE


