---
# copyright Utrecht University

- name: Checkout Yoda Zabbix scripts and rules
  become_user: "{{ irods_service_account }}"
  become: yes
  git:
    repo: "https://github.com/UtrechtUniversity/yoda-zabbix.git"
    dest: "/etc/irods/yoda-zabbix/src"
    version: "{{ yoda_version }}"
  register: zabbix_repo


- name: Ensure zabbix_agentd.userparams.conf exists
  stat: path=/etc/irods/yoda-zabbix/zabbix_agentd.userparams.conf
  register: zabbix_agentd


- name: Copy zabbix_agentd.userparams.conf to right place
  command: cp /etc/irods/yoda-zabbix/src/zabbix_agentd.userparams.conf /etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf
  when: not zabbix_agentd.stat.exists or zabbix_repo.changed


- name: Ensure right file ownership on zabbix_agentd.userparams.conf
  file:
    path: /etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf
    owner: zabbix
    group: zabbix
    mode: 0400


- name: Ensure yoda-zabbix-sudoers exists
  stat: path=/etc/sudoers.d/yoda-zabbix-sudoers
  register: zabbix_sudoers


- name: Copy yoda-zabbix-sudoers to right place
  command: cp /etc/irods/yoda-zabbix/src/yoda-zabbix-sudoers /etc/sudoers.d/yoda-zabbix-sudoers
  when: not zabbix_sudoers.stat.exists or zabbix_repo.changed


- name: Ensure right file ownership on zabbix_agentd.userparams.conf
  file:
    path: /etc/sudoers.d/yoda-zabbix-sudoers
    owner: root
    group: root
    mode: 0440


- name: Copy Yoda Zabbix rules
  shell: "cp /etc/irods/yoda-zabbix/src/*.r /etc/zabbix/zabbix_agentd.d/"
  when: zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Copy Yoda Zabbix scripts
  shell: "cp /etc/irods/yoda-zabbix/src/*.sh /etc/zabbix/zabbix_agentd.d/"
  when: zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Find Yoda Zabbix rules
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.r"
  register: yoda_zabbix_rules


- name: Ensure right file ownership on Yoda Zabbix rules
  file:
    path: "{{ item.path }}"
    owner: irods
    group: irods
    mode: 0500
  with_items: "{{ yoda_zabbix_rules.files }}"


- name: Find Yoda Zabbix scripts
  find:
    paths: /etc/zabbix/zabbix_agentd.d
    patterns: "*.sh"
  register: yoda_zabbix_scripts


- name: Ensure right file ownership on Yoda Zabbix scripts
  file:
    path: "{{ item.path }}"
    owner: zabbix
    group: zabbix
    mode: 0500
  with_items: "{{ yoda_zabbix_scripts.files }}"

