---
# copyright Utrecht University

- name: Checkout Yoda Zabbix scripts and rules
  become_user: "{{ irods_service_account }}"
  become: yes
  git:
    repo: "https://github.com/UtrechtUniversity/yoda-zabbix.git"
    dest: "/etc/irods/yoda-zabbix/src"
    version: "{{ zabbix_version }}"
  register: zabbix_repo


- name: Ensure zabbix_agentd.userparams.conf exists
  stat: path=/etc/irods/yoda-zabbix/zabbix_agentd.userparams.conf
  register: zabbix_agentd


- name: Copy zabbix_agentd.userparams.conf to right place
  command: cp /etc/irods/yoda-zabbix/src/zabbix_agentd.userparams.conf /etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf
  when: not zabbix_agentd.stat.exists or zabbix_repo.changed


- name: Ensure right file ownership on zabbix_agentd.userparams.conf
  file:
    path: /etc/zabbix/zabbix_agentd.d/zabbix_agentd.userparams.conf
    owner: zabbix
    group: zabbix
    mode: 0400


- name: Ensure yoda-zabbix-sudoers exists
  stat: path=/etc/sudoers.d/yoda-zabbix-sudoers
  register: zabbix_sudoers


- name: Copy yoda-zabbix-sudoers to right place
  command: cp /etc/irods/yoda-zabbix/src/yoda-zabbix-sudoers /etc/sudoers.d/yoda-zabbix-sudoers
  when: not zabbix_sudoers.stat.exists or zabbix_repo.changed


- name: Ensure right file ownership on zabbix_agentd.userparams.conf
  file:
    path: /etc/sudoers.d/yoda-zabbix-sudoers
    owner: root
    group: root
    mode: 0440


- name: Copy Yoda Zabbix rules
  shell: "cp /etc/irods/yoda-zabbix/src/*.r /etc/zabbix/zabbix_agentd.d/"
  when: zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Copy Yoda Zabbix scripts
  shell: "cp /etc/irods/yoda-zabbix/src/*.sh /etc/zabbix/zabbix_agentd.d/"
  when: zabbix_repo.changed
  notify: Restart Zabbix agent


- name: Ensure right file ownership on Yoda Zabbix rules
  file:
    path: "/etc/zabbix/zabbix_agentd.d/{{ item }}"
    owner: irods
    group: irods
    mode: 0500
  with_items:
    - monitorDelayedRules.r
    - monitorPublicationsPending.r
    - listOrphanedGroups.r


- name: Ensure right file ownership on Yoda Zabbix scripts
  file:
    path: "//etc/zabbix/zabbix_agentd.d/{{ item }}"
    owner: zabbix
    group: zabbix
    mode: 0500
  with_items:
    - externalUsersCount.sh
    - internalUsersCount.sh
    - irodsGroupsCount.sh
    - monitorDelayedRules.sh
    - monitorPublicationsPending.sh
    - concurrentiRodsClientConnections.sh
    - concurrentiRodsUsers.sh
    - dailyRodslogErrors.sh
    - hourlyRodslogErrors.sh
    - monitorKilledProcesses.sh
    - listOrphanedGroups.sh
    - replicationErrors.sh
    - testUserParam.sh
