---
# copyright Utrecht University

- name: Insert host entries for every development server
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }}
      {{ hostvars[item].ansible_fqdn }}
      {{ hostvars[item].ansible_hostname }}"
    state: present
  with_items: "{{ groups.development }}"
