---
# copyright Utrecht University

- name: Check if Zabbix agent is installable from repository
  yum:
    list: '{{ zabbix_agent.package }}'
  register: zabbix_agent_repo


- name: Download Zabbix agent rpm
  get_url:
    url: '{{ zabbix_agent.url }}/{{ zabbix_agent.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ zabbix_agent.filename }}'
    checksum: '{{ zabbix_agent.checksum }}'
  when: not zabbix_agent_repo.results


- name: Install Zabbix agent from downloaded rpm
  package:
    name: '{{ rpm_dest_dir }}/{{ zabbix_agent.filename }}'
    state: present
  when: not zabbix_agent_repo.results


- name: Ensure Zabbix agent rpm is installed
  package:
    name: '{{ zabbix_agent.package }}'
    state: present
  when: zabbix_agent_repo.results


- name: Enable the Zabbix agent service
  service:
    name: zabbix-agent
    enabled: yes
    use: service


- name: Allow Zabbix agent to start
  selinux_permissive:
    name: zabbix_agent_t
    permissive: true
  when: ansible_selinux


- name: Allow access to port 10050 (Zabbix active checks) in firewall
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
    immediate: yes
  notify: Restart firewall


- name: Allow access to port 10051 (Zabbix passive checks) in firewall
  firewalld:
    port: 10051/tcp
    permanent: true
    state: enabled
    immediate: yes
  notify: Restart firewall


- name: Generate Zabbix agent PSK
  shell: openssl rand -hex 256 > /etc/zabbix/zabbix_agentd.psk
    creates=/etc/zabbix/zabbix_agentd.psk
  when: not ansible_check_mode


- name: Configure Zabbix agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Zabbix agent


- name: Checkout Yoda Zabbix scripts and rules
  become_user: "{{ irods_service_account }}"
  become: yes
  git:
    repo: "https://github.com/UtrechtUniversity/yoda-zabbix.git"
    dest: "/etc/irods/yoda-zabbix"
    version: "{{ yoda_version }}"
