---
# copyright Utrecht University

yoda_version: development
irods_service_account: irods

# Ruleset configuration.
core_rulesets:
  - name: irods-ruleset-uu
    repo: https://github.com/UtrechtUniversity/irods-ruleset-uu.git
    ruleset_name: rules-uu
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: core
    ruleset_name: core
    path: /etc/irods/core.re
    install_scripts: no

extra_rulesets:

# Research module specific configuration.
default_yoda_schema: default-0   # Default Yoda metadata scheme: default-0 or default-1
enable_revisions: 1              # Enable revisions: yes (1) or no (0)
revision_strategy: B             # Revision strategy: A, B, J or Simple
yoda_instance: "{{ instance }}"
update_rulesets: yes             # Update already installed rulesets with git
update_schemas: 0                # Update already installed schemas, formelements and stylesheets: yes (1) or no (0)
yoda_random_id_length: 6         # Length of random ID to add to persistent identifier
irods_default_resc: irodsResc

#####################
# Mail notifications
#####################
send_notifications: 0               # Enable notifications: yes (1) or no (0)
sender_email: noreply@yoda.test     # Sender email address
sender_name: "Yoda system"          # Sender name
reply_to: noreply@yoda.test         # Reply-To email address
smtp_server: PLACEHOLDER            # SMTP server to send mail to
smtp_username: PLACEHOLDER          # SMTP server username
smtp_password: PLACEHOLDER          # SMTP server password
