---
# copyright Utrecht University

yoda_version: development
update_rulesets: no

# Ruleset configuration.
rulesets:
  - name: irods-ruleset-i-lab
    repo: https://github.com/UtrechtUniversity/irods-ruleset-i-lab.git
    ruleset_name: rules-i-lab
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: irods-ruleset-research
    repo: https://github.com/UtrechtUniversity/irods-ruleset-research.git
    ruleset_name: rules-research
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: irods-ruleset-uu
    repo: https://github.com/UtrechtUniversity/irods-ruleset-uu.git
    ruleset_name: rules-uu
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: core
    ruleset_name: core
    path: /etc/irods/core.re
    install_scripts: no

# Research module specific configuration.
default_yoda_schema: default
enable_revisions: 1
revision_strategy: A
yoda_instance: "{{ instance }}"
update_schemas: 0
irods_default_resc: irodsResc

#####################
# Mail notifications
#####################
send_notifications: 0               # Enable notifications: yes (1) or no (0)
sender_email: noreply@yoda.test     # Sender email address
sender_name: "Yoda system"          # Sender name
smtp_server: PLACEHOLDER            # SMTP server to send mail to
smtp_username: PLACEHOLDER          # SMTP server username
smtp_password: PLACEHOLDER          # SMTP server password
