---
# copyright Utrecht University

yoda_deployment_user: yodadeployment
yoda_version: development
yoda_eus_fqdn: eus.yoda.test

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt
