---
# copyright Utrecht University

- name: Install python-irodsclient dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-six
    - python-prettytable


- name: Check if python-irodsclient is installable from repository
  yum:
    list: '{{ python_irodsclient.package }}'
  register: python_irodsclient_repo


- name: Download python-irodsclient rpm
  get_url:
    url: '{{ python_irodsclient.url }}/{{ python_irodsclient.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ python_irodsclient.filename }}'
    checksum: '{{ python_irodsclient.checksum }}'
  when: not python_irodsclient_repo.results


- name: Install python-irodsclient from downloaded rpm
  package:
    name: '{{ rpm_dest_dir }}/{{ python_irodsclient.filename }}'
    state: present
  when: not python_irodsclient_repo.results


- name: Ensure python-irodsclient is installed from repository
  package:
    name: '{{ python_irodsclient.package }}'
    state: present
  when: python_irodsclient_repo.results
