---
# copyright Utrecht University

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# davrods rpm location and checksum
davrods:
  url: https://github.com/UtrechtUniversity/davrods/releases/download/4.2.1_1.1.1
  filename: davrods-4.2.1_1.1.1-1.rpm
  checksum: sha256:3beb6f4bd08c2e775fdc9002474f0771de327b7712972abf6ce6f6fa54dff562

yoda_davrods_fqdn: data.yoda.test           # Yoda Davrods WebDAV fully qualified domain name (FQDN)
yoda_davrods_port: 443

yoda_davrods_anonymous_fqdn: public.data.yoda.test
yoda_davrods_anonymous_port: 443

yoda_portal_fqdn: portal.yoda.test          # Yoda Portal fully qualified domain name (FQDN)

# iRODS configuration.
irods_icat_fqdn: icat.yoda.test
irods_authentication_scheme: Native        # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_default_resc: irodsResc              # iRODS default resource name
irods_icat_port: 1247

# OpenSSL configuration.
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt
openssl_dhparams: dhparams.pem
