---
# copyright Utrecht University

- name: Ensure Yoda MOAI prerequisites are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - python-pip
  - python-virtualenv
  - python-lxml
  - python-sqlalchemy
  - mod_wsgi


- name: Ensure yodadeployment has access to /var/www/yoda
  file:
    path: /var/www/yoda
    state: directory
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: 0755


- name: Check out YoDa MOAI from github
  become_user: "{{ yoda_deployment_user }}"
  become: yes
  git:
    repo: https://github.com/UtrechtUniversity/yoda-moai.git
    dest: /var/www/yoda/moai/yoda-moai


- name: Install YoDA MOAI in virtualenv
  pip:
    name: /var/www/yoda/moai/yoda-moai/
    extra_args: -e
    virtualenv: "{{ yoda_moai_virtualenv }}"
    virtualenv_site_packages: yes
  notify: Restart Apache webserver


- name: Copy Yoda MOAI Apache configuration
  template:
    src: yoda-moai-vhost.conf.j2
    dest: /etc/httpd/conf.d/yoda-moai-vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache webserver


- name: Install moai.wsgi
  template:
    src: moai.wsgi.j2
    dest: /var/www/yoda/moai/moai.wsgi
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: 0644
  notify: Restart Apache webserver


- name: Install settings.ini for MOAI
  template:
    src: moai-settings.ini.j2
    dest: "{{ yoda_moai_settings_ini }}"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: 0644
  notify: Restart Apache webserver
 
- name: Set SELinux context for moai directory
  sefcontext:
    target: '/var/www/yoda/moai'
    setype: httpd_sys_rw_content_t
    state: present


- name: Configure cronjob to update MOAI database
  cron:
    user: "{{ yoda_deployment_user }}"
    name: 'cronjob-update-moai'
    minute: '*/5'
    job: '{{ yoda_moai_virtualenv }}/bin/update_moai  --config {{ yoda_moai_settings_ini }} yoda >> /var/www/yoda/update_moai.log'
