---
# copyright Utrecht University

- name: Ensure davrods prerequisites are installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - boost
  - jansson


- name: Download davrods rpm
  get_url:
    url: '{{ davrods.url }}/{{ davrods.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ davrods.filename }}'
    checksum: '{{ davrods.checksum }}'


- name: Ensure davrods rpm is installed
  package:
    name: '{{ rpm_dest_dir }}/{{ davrods.filename }}'
    state: present


- name: Allow Apache to execute davrods module
  sefcontext:
    target: /etc/httpd/modules/mod_davrods.so
    setype: httpd_sys_script_exec_t
    state: present


- name: Copy irods_enviroment.json to /etc/httpd/irods/irods_environment.json
  template:
    src: irods_environment.j2
    dest: /etc/httpd/irods/irods_environment.json
    owner: apache
    group: apache
    mode: 0644
  notify: Restart Apache webserver


- name: Copy davrods Apache configuration
  template:
    src: davrods-vhost.conf.j2
    dest: /etc/httpd/conf.d/davrods-vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Apache webserver


- name: Allow Apache to execute iRODS network plugins
  sefcontext:
    target: '{{ item }}'
    setype: httpd_sys_script_exec_t
    state: present
  with_items:
    - /var/lib/irods/plugins/network/libtcp.so
    - /var/lib/irods/plugins/network/libssl.so


- name: Allow public to ports for davrods in firewall
  firewalld:
    port: '{{ yoda_davrods_port }}/tcp'
    permanent: true
    state: enabled
    immediate: yes
  notify: Restart firewall
