---
# copyright Utrecht University

- name: Restart ntp
  service:
    name: ntpd
    state: restarted


- name: Restart firewall
  service:
    name: firewalld
    state: restarted


- name: Clean yum metadata cache
  command: yum clean metadata
  args:
    warn: no
