---
# copyright Utrecht University

- name: Ensure iRODS 4.2.5 packages are absent
  package:
    name:
      - irods-uu-microservices-4.2.5_0.8.0-1
      - irods-sudo-microservices-4.2.5_1.0.0-1
      - davrods-4.2.5_1.4.2-1
      - irods-uu-microservices-4.2.5_0.7.11-1
    state: absent


- name: Ensure iRODS runtime is installed
  package:
    name: irods-runtime-4.2.6-1.x86_64 
    state: present
