---
# copyright Utrecht University

- name: Download iRODS runtime rpm
  get_url:
    url='{{ irods_rpm_ftp }}/{{ irods_runtime_rpm }}'
    dest='{{ rpm_dest_dir }}/{{ irods_runtime_rpm }}'


- name: Ensure iRODS runtime is installed
  yum:
    name='{{ item }}'
    state=present
  with_items:
    - '{{ rpm_dest_dir }}/{{ irods_runtime_rpm }}'
