---
# copyright Utrecht University

- name: Ensure iRODS 4.2.4 packages are absent
  package:
    name:
      - irods-uu-microservices-4.2.4_0.7.10-1
      - irods-uu-microservices-4.2.4_0.7.11-1
      - irods-sudo-microservices-4.2.4_1.0.0-1
      - davrods-4.2.4_1.4.1-1
      - davrods-4.2.4_1.4.2-1
    state: absent


- name: Ensure iRODS runtime is installed
  package:
    name: irods-runtime-4.2.5-1
    state: present


# TEMPORARY: Download iRODS runtime 4.2.6 preview with hot fix.
- name: Download iRODS runtime 4.2.6 preview release with hot fix
  get_url:
    url: 'https://people.renci.org/~alanking/utrecht-4.2.6-preview/irods-runtime-4.2.5-1.x86_64.rpm'
    dest: '/tmp/irods-runtime-4.2.5-1.x86_64.rpm'
    checksum: 'sha256:7fdf063695ce40d2efbdec0cfc94efa885c3abe75cdd4a45a3936b562e47be95'


# TEMPORARY: Install iRODS runtime 4.2.6 preview with hot fix.
- name: Install iRODS runtime 4.2.6 preview release with hot fix
  command: rpm -i https://people.renci.org/~alanking/utrecht-4.2.6-preview/irods-runtime-4.2.5-1.x86_64.rpm --force
