---
# copyright Utrecht University

- name: Download iRODS runtime rpm
  get_url:
    url: '{{ irods_runtime.url }}/{{ irods_runtime.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ irods_runtime.filename }}'
    checksum: '{{ irods_runtime.checksum }}'


- name: Ensure iRODS runtime is installed
  package:
    name: '{{ rpm_dest_dir }}/{{ irods_runtime.filename }}'
    state: present
