---
# copyright Utrecht University

- name: Check if iRODS runtime is installable from repository
  yum:
    list: '{{ irods_runtime.package }}'
  register: irods_runtime_repo


- name: Download iRODS runtime rpm
  get_url:
    url: '{{ irods_runtime.url }}/{{ irods_runtime.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ irods_runtime.filename }}'
    checksum: '{{ irods_runtime.checksum }}'
  when: not irods_runtime_repo.results


- name: Install iRODS runtime from downloaded rpm
  yum:
    name: '{{ rpm_dest_dir }}/{{ irods_runtime.filename }}'
    state: present
  when: not irods_runtime_repo.results


- name: Ensure iRODS runtime is installed
  package:
    name: '{{ irods_runtime.package }}'
    state: present
  when: irods_runtime_repo.results
