---
# copyright Utrecht University

- name: Ensure iRODS 4.1 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - irods-runtime-4.1.11-0
    - davrods-4.1_1.3.0-1


- name: Ensure iRODS 4.2.3 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - irods-uu-microservices-4.2.3_0.7.8-1
    - irods-sudo-microservices-4.2.3_1.0.0-1
    - davrods-4.2.3_1.4.1-1


- name: Ensure iRODS runtime is installed
  package:
    name: irods-runtime-4.2.4-1
    state: present
  when: not ansible_check_mode