---
# ansible tasks within this role
# copyright Utrecht University

- name: Download iRODS iCAT server rpm
  get_url: 
    url='{{irods_rpm_ftp}}/{{irods_icat_rpm}}'
    dest='{{rpm_dest_dir}}/'


- name: Download iRODS database plugin rpm
  get_url: 
    url='{{irods_rpm_ftp}}/{{irods_db_rpm}}'
    dest='{{rpm_dest_dir}}/'


- name: Install iRODS iCAT server dependencies
  yum:
    name='{{item}}'
    state=present
  with_items:
    - epel-release
    
    
- name: Install iRODS iCAT server and database plugin
  yum: 
    name='{{item}}'
    state=present
  with_items:
    - '{{rpm_dest_dir}}/{{irods_icat_rpm}}'
    - '{{rpm_dest_dir}}/{{irods_db_rpm}}'


- name: Copy responses for setup_irods.sh
  template: src=setup_irods.j2 dest=/home/{{ ansible_ssh_user }}/setup_irods

- name: Configure iRODS iCAT server
  shell:
    /var/lib/irods/packaging/setup_irods.sh < /home/{{ ansible_ssh_user }}/setup_irods
  run_once: true