---
# ansible tasks within this role
# copyright Utrecht University

- name: Download iRODS iCAT server rpm
  get_url: 
    url='{{irods_rpm_ftp}}/{{irods_icat_rpm}}'
    dest='{{rpm_dest_dir}}/'


- name: Download iRODS database plugin rpm
  get_url: 
    url='{{irods_rpm_ftp}}/{{irods_db_rpm}}'
    dest='{{rpm_dest_dir}}/'


- name: Install iRODS icat iCAT server dependencies
  yum:
    name='{{item}}'
    state=present
  with_items:
    - epel-release
    
    
- name: Install iRODS iCAT server and database plugin
  yum: 
    name='{{item}}'
    state=present
  with_items:
    - '{{rpm_dest_dir}}/{{irods_icat_rpm}}'
    - '{{rpm_dest_dir}}/{{irods_db_rpm}}'
