---
# ansible tasks within this role
# copyright Utrecht University

- name: Download iRODS iCAT server rpm
  get_url:
    url='{{ irods_rpm_ftp }}/{{ irods_icat_rpm }}'
    dest='{{ rpm_dest_dir }}/{{ irods_icat_rpm }}'
    checksum='{{ irods_icat_rpm_sha256 }}'


- name: Download iRODS database plugin rpm
  get_url:
    url='{{ irods_rpm_ftp }}/{{ irods_db_rpm }}'
    dest='{{ rpm_dest_dir }}/{{ irods_db_rpm }}'
    checksum='{{ irods_db_rpm_sha256 }}'


- name: Install iRODS iCAT server dependencies
  yum:
    name='{{ item }}'
    state=present
  with_items:
    - epel-release


- name: Install iRODS iCAT server and database plugin
  yum:
    name='{{ item }}'
    state=present
  with_items:
    - '{{ rpm_dest_dir }}/{{ irods_icat_rpm }}'
    - '{{ rpm_dest_dir }}/{{ irods_db_rpm }}'


- name: Generate zone key
  command: 'openssl rand -hex 16'
  register: zone_key
  args:
    creates: /home/{{ ansible_ssh_user }}/setup_irods


- name: Store zone key in variable
  set_fact:
    irods_zone_key: '{{ zone_key.stdout }}'


- name: Generate negotiation key
  command: 'openssl rand -hex 16'
  register: negotiation_key
  args:
    creates: /home/{{ ansible_ssh_user }}/setup_irods


- name: Store negotiation key in variable
  set_fact:
    irods_negotiation_key: '{{ negotiation_key.stdout }}'


- name: Generate control plane key
  command: 'openssl rand -hex 16'
  register: control_plane_key
  args:
    creates: /home/{{ ansible_ssh_user }}/setup_irods


- name: Store control plane key in variable
  set_fact:
    irods_control_plane_key: '{{ control_plane_key.stdout }}'


- name: Copy responses for setup_irods.sh
  template:
    src: setup_irods.j2
    dest: /home/{{ ansible_ssh_user }}/setup_irods
    force: no


- name: Configure iRODS iCAT server
  shell:
    /var/lib/irods/packaging/setup_irods.sh < /home/{{ ansible_ssh_user }}/setup_irods
  args:
    creates: /etc/irods/service_account.config
  run_once: true