---
# copyright Utrecht University

- name: Ensure iRODS iCommands are absent, are included in the iCAT server
  package:
    name: 'irods-icommands'
    state: absent


- name: Ensure iRODS 4.1 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - irods-server-4.1.11
    - irods-database-plugin-postgres-4.1.11


- name: Ensure iRODS iCAT server and database plugin are present
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - irods-server-4.2.1-1
    - irods-database-plugin-postgres-4.2.1-1


- name: Generate zone key
  command: 'openssl rand -hex 16'
  register: zone_key
  args:
    creates: /etc/irods/setup_irods


- name: Generate negotiation key
  command: 'openssl rand -hex 16'
  register: negotiation_key
  args:
    creates: /etc/irods/setup_irods


- name: Generate control plane key
  command: 'openssl rand -hex 16'
  register: control_plane_key
  args:
    creates: /etc/irods/setup_irods


- name: Generate password salt
  command: 'openssl rand -hex 16'
  register: password_salt
  args:
    creates: /etc/irods/setup_irods


- name: Store iCAT keys in variables
  set_fact:
    '{{ item.fact }}': '{{ item.key }}'
  with_items:
    - fact: irods_zone_key
      key: '{{ zone_key.stdout }}'
    - fact: irods_negotiation_key
      key: '{{ negotiation_key.stdout }}'
    - fact: irods_control_plane_key
      key: '{{ control_plane_key.stdout }}'
    - fact: irods_password_salt
      key: '{{ password_salt.stdout }}'
  when: not ansible_check_mode


- name: Copy responses for setup_irods.sh
  template:
    src: setup_irods.j2
    dest: /etc/irods/setup_irods
    force: no
  when: not ansible_check_mode


- name: Configure iRODS iCAT server
  shell: sudo python /var/lib/irods/scripts/setup_irods.py
    < /etc/irods/setup_irods
  args:
    creates: /etc/irods/service_account.config
  run_once: true
  when: not ansible_check_mode


- name: Ensure iRODS server is up
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: 'ils /{{ irods_zone }}/home'
  register: ils
  ignore_errors: true
  changed_when: ils | failed


- name: Start iRODS server
  become_user: '{{ irods_service_account }}'
  become: yes
  command: '/var/lib/irods/irodsctl start'
  when: ils | failed


- name: Wait until iRODS server is ready to receive requests
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: 'ils /{{ irods_zone }}/home'
  register: ils
  until: ils | succeeded
  retries: 5
  delay: 10
  when: ils | failed


- name: Ensure all users have iRODS read access on /zone/home
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: 'ils -A /{{ irods_zone }}/home | grep "g:public#"'
  register: read_access
  ignore_errors: true
  changed_when: read_access | failed


- name: Provide iRODS read access for all users on /zone/home
  become_user: '{{ irods_service_account }}'
  become: yes
  command: 'ichmod -M read public /{{ irods_zone }}/home'
  when: read_access | failed


- name: Enable ports for iCAT in firewall
  firewalld:
    port: '{{ item }}'
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - '{{ irods_icat_port }}/tcp'
    - '{{ irods_port_range_begin }}-{{ irods_port_range_end }}/tcp'
  notify: Restart firewall


- name: Ensure host has private key file
  copy:
    dest: "{{ hostvars[item]['pki_certs']['results'][0]['item'] }}"
    content: >
      {{ hostvars[item]['pki_certs']['results'][0]['content'] | b64decode }}
    owner: root
    group: root
    mode: 0600
  with_inventory_hostnames:
    - 'portals:&{{ instance }}'


- name: Ensure host has Diffie-Hellman parameters
  copy:
    dest: "{{ hostvars[item]['pki_certs']['results'][1]['item'] }}"
    content: >
      {{ hostvars[item]['pki_certs']['results'][1]['content'] | b64decode }}
    owner: root
    group: root
    mode: 0600
  with_inventory_hostnames:
    - 'portals:&{{ instance }}'


- name: Ensure host has certificate file
  copy:
    dest: "{{ hostvars[item]['pki_certs']['results'][2]['item'] }}"
    content: >
      {{ hostvars[item]['pki_certs']['results'][2]['content'] | b64decode }}
    owner: root
    group: root
    mode: 0600
  with_inventory_hostnames:
    - 'portals:&{{ instance }}'


- name: Ensure private key file is available for iRODS
  command: 'cp {{ openssl_private_dir }}/{{ openssl_key_signed }} {{ openssl_key_signed }}'
  args:
    chdir: '/etc/irods'
    creates: '{{ openssl_key_signed }}'


- name: Ensure Diffie-Hellman parameters are available for iRODS
  command: 'cp {{ openssl_private_dir }}/{{ openssl_dhparams }} {{ openssl_dhparams }}'
  args:
    chdir: '/etc/irods'
    creates: '{{ openssl_dhparams }}'


- name: Ensure certificate file is available for iRODS
  command: 'cp {{ openssl_certs_dir }}/{{ openssl_crt_signed }} {{ openssl_crt_signed }}'
  args:
    chdir: '/etc/irods'
    creates: '{{ openssl_crt_signed }}'


- name: Ensure iRODS has access to PKI files
  file:
    path: '{{ item }}'
    mode: 0600
    group: '{{ irods_service_account }}'
    owner: '{{ irods_service_account }}'
    state: file
  with_items:
    - '/etc/irods/{{ openssl_key_signed }}'
    - '/etc/irods/{{ openssl_dhparams }}'
    - '/etc/irods/{{ openssl_crt_signed }}'


- name: Ensure iRODS is configured to use SSL
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_config:
    path: '/var/lib/irods/.irods/irods_environment.json'
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items:
    - key: 'irods_ssl_certificate_chain_file'
      value: '/etc/irods/{{ openssl_crt_signed }}'
    - key: 'irods_ssl_certificate_key_file'
      value: '/etc/irods/{{ openssl_key_signed }}'
    - key: 'irods_ssl_dh_params_file'
      value: '/etc/irods/{{ openssl_dhparams }}'
    - key: 'irods_client_server_policy'
      value: 'CS_NEG_REQUIRE'
    - key: 'irods_ssl_verify_server'
      value: 'none'


- name: Ensure iRODS is configured to use SSL connection to database
  ini_file:
    path: /var/lib/irods/.odbc.ini
    section: postgres
    option: 'sslmode'
    value: 'require'
    mode: 0600


- name: Ensure irods .ssh directory has strict permissions
  file:
    path: /var/lib/irods/.ssh
    state: directory
    mode: 0700
    owner: '{{irods_service_account }}'
    group: '{{irods_service_account }}'


- name: Install private upload key
  become_user: '{{ irods_service_account }}'
  become: yes
  copy:
    content: '{{ upload_priv_key | b64decode }}'
    dest: '/var/lib/irods/.ssh/id_ed25519'
    owner: '{{ irods_service_account }}'
    mode: 0600
  when: upload_priv_key is defined


- name: Scan public host pub key
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: "ssh-keyscan {{ yoda_public_host }} >> ~/.ssh/known_hosts"
  args:
    creates: '/var/lib/irods/.ssh/known_hosts'
  when: upload_priv_key is defined

# TODO fix for iRODS 4.2 compatibility
# - name: Ensure Yoda anonymous user exists
#   become_user: '{{ irods_service_account }}'
#   become: yes
#   irods_mkuser:
#     name: anonymous
#
#
# - name: Ensure Yoda anonymous user exists
#   become_user: '{{ irods_service_account }}'
#   become: yes
#   command: 'iadmin mkuser anonymous rodsuser'


- name: Ensure anonymous user has iRODS read access on /zone/home
  become_user: '{{ irods_service_account }}'
  become: yes
  shell: 'ils -A /{{ irods_zone }}/home | grep "anonymous#"'
  register: read_access
  ignore_errors: true
  changed_when: read_access | failed


- name: Provide iRODS read access for anonymous user on /zone/home
  become_user: '{{ irods_service_account }}'
  become: yes
  command: 'ichmod -M read anonymous /{{ irods_zone }}/home'
  when: read_access | failed


- include_tasks: setup_pam_radius.yml
  when: irods_authentication_scheme == "PAM"
