---
# copyright Utrecht University

- name: Ensure PAM radius is installed
  package:
    name: pam_radius
    state: present


- name: Ensure /etc/pam.d/irods is configured
  template:
    src='irods_pam.j2'
    dest='/etc/pam.d/irods'


- name: Ensure /etc/pam_radius.conf is configured
  template:
    src='pam_radius.conf.j2'
    dest='/etc/pam_radius.conf'


- name: Ensure iRODS is configured to use PAM
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_config:
    path: '/var/lib/irods/.irods/irods_environment.json'
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items:
    - key: 'irods_authentication_scheme'
      value: '{{ irods_authentication_scheme }}'
