---
# copyright Utrecht University

- name: Password protect iCAT connections
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all {{ hostvars[item].ansible_host }}/32 md5"
  with_items: "{{ groups['icats'] }}"
  notify: Restart PostgreSQL


- name: Create iCAT database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ irods.database.name }}"
    encoding: UTF-8
    template: template0


- name: Create iRods database user
  become_user: postgres
  become: yes
  postgresql_user:
    db: "{{ irods.database.name }}"
    name: "{{ irods.database.user }}"
    password: "{{ irods.database.password }}"
    priv: ALL
