---
# copyright Utrecht University

- name: Password protect iCAT connections
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all {{ hostvars[item]['ansible_default_ipv4']['address'] }}/32 md5"
  with_inventory_hostnames:
    - 'icats:&{{ instance }}'
  notify: Restart PostgreSQL


- name: Create iCAT database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ irods_database_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0


- name: Create iRods database user
  become_user: postgres
  become: yes
  postgresql_user:
    db: "{{ irods_database_name }}"
    name: "{{ irods_database_user }}"
    password: "{{ irods_database_password }}"
    priv: ALL
