---
# ansible tasks within this role
# copyright Utrecht University

- name: Install PostgreSQL
  package: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-contrib


- name: Install ansible PostgreSQL modules prerequisites
  package: name={{ item }} state=present
  with_items:
    - postgresql-devel
    - python-psycopg2


- name: Initiate database
  command: postgresql-setup initdb
           creates=/var/lib/pgsql/data/postgresql.conf


- name: Ensure PostgreSQL is enabled and started
  service: name=postgresql enabled=yes state=started


- name: Set authentication to MD5 for local connections (IPv4)
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32'
    line: 'host all all 127.0.0.1/32 md5'
  notify: Restart PostgreSQL


- name: Set authentication to MD5 for local connections (IPv6)
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    regexp: 'host\s+all\s+all\s+::1/128'
    line: 'host all all ::1/128 md5'
  notify: Restart PostgreSQL


- name: Add MD5 authentication for iCAT server(s)
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all {{ hostvars[item].ansible_host }}/32 md5"
  with_items: "{{ groups['icat'] }}"
  notify: Restart PostgreSQL


- name: Listen on all interfaces
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    line: "listen_addresses = '*'"
  notify: Restart PostgreSQL


- name: Allow access to port 5432 in firewall
  firewalld: port=5432/tcp permanent=true state=enabled immediate=yes
  notify: Restart firewall


- name: Create iCAT database
  become_user: postgres
  become: yes
  postgresql_db:
    name: ICAT
    encoding: UTF-8
    template: template0


- name: Create iRods database  user
  become_user: postgres
  become: yes
  postgresql_user:
    db: ICAT
    name: "{{ irods_database_user }}"
    password: "{{ irods_database_password }}"
    priv: ALL
