---
# copyright Utrecht University

- name: Password protect iCAT connections
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all {{ hostvars[icat_host].ansible_host }}/32 md5"
  notify: Restart PostgreSQL
