---
# copyright Utrecht University

- name: Password protect iCAT connections
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: "host all all {{ item }}/32 md5"
  with_items: "{{ hostvars[icat_host].ansible_all_ipv4_addresses }}"
  notify: Restart PostgreSQL
