---
# copyright Utrecht University

- name: Download iRODS resource server rpm
  get_url:
    url='{{ irods_rpm_ftp }}/{{ irods_resource_rpm }}'
    dest='{{ rpm_dest_dir }}/{{ irods_resource_rpm }}'


- name: Ensure iRODS resource server is installed
  yum:
    name='{{ item }}'
    state=present
  with_items:
    - '{{ rpm_dest_dir }}/{{ irods_resource_rpm }}'
