---
# copyright Utrecht University

- name: Check if iRODS resource server is installable from repository
  yum:
    list: '{{ irods_resource.package }}'
  register: irods_resource_repo


- name: Download iRODS resource server rpm
  get_url:
    url: '{{ irods_resource.url }}/{{ irods_resource.filename }}'
    dest: '{{ rpm_dest_dir }}/{{ irods_resource.filename }}'
    checksum: '{{ irods_resource.checksum }}'
  when: not irods_resource_repo.results


- name: Install iRODS resource server from downloaded rpm
  package:
    name: '{{ rpm_dest_dir }}/{{ irods_resource.filename }}'
    state: present
  when: not irods_resource_repo.results


- name: Ensure iRODS resource server is installed
  package:
    name: '{{ irods_resource.package }}'
    state: present
  when: irods_resource_repo.results


- name: Create iRODS service account group
  group:
    name: '{{ irods_service_account }}'
    state: present


- name: Create iRODS service account user
  user:
    name: '{{ irods_service_account }}'
    group: '{{ irods_service_account }}'
    comment: 'iRODS Administrator'
    home: /var/lib/irods
    shell: /bin/bash
    password: '!locked!'
    update_password: on_create
    state: present


- name: Make iRODS service account owner of iRODS directories
  file:
    group: '{{ irods_service_account }}'
    owner: '{{ irods_service_account }}'
    recurse: yes
    path: '{{ item }}'
  with_items:
  - /var/lib/irods
  - /etc/irods
