---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed
  yum: name={{ item }} state=present
  with_items:
  - libsemanage-python
  - libselinux-python


- name: Ensure basics (vim, bind-utils, etc.) are installed
  yum: name={{ item }} state=present
  with_items:
    - bind-utils
    - vim
    - htop
    - git

