---
# copyright Utrecht University

- name: Read the current hostname configured in /etc/hosts
  command: 'hostname --fqdn'
  register: hostname
  changed_when: hostname.stdout != inventory_hostname


- name: Ensure FQDN is defined as hostname in /etc/hosts
  command: hostnamectl set-hostname {{ inventory_hostname }}
  when: hostname.stdout != inventory_hostname
