---
# copyright Utrecht University

- name: Read the current hostname configured in /etc/hosts
  command: 'hostname --fqdn'
  register: hostname
  changed_when: hostname.stdout == 'localhost'


- name: Ensure FQDN is defined as hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1\s+localhost(.*)$'
    state: present
    backrefs: yes
    line: '127.0.0.1\t{{ansible_fqdn}} \1'
    backup: yes
  when: hostname.stdout == 'localhost'
