---
# copyright Utrecht University

- name: Read the current hostname configured in /etc/hosts
  command: 'hostname --fqdn'
  register: hostname
  changed_when: hostname.stdout != ansible_fqdn


- name: Ensure FQDN is defined as hostname in /etc/hosts
  command: hostnamectl set-hostname {{ ansible_fqdn }}
  when: hostname.stdout != ansible_fqdn
