---
# ansible tasks within this role
# copyright Utrecht University

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp


- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: Restart ntp


- name: Ensure the ntp service is running and enabled
  service: name=ntpd state=started enabled=yes
  tags: ntp
