---
# copyright Utrecht University

- name: Ensure pip is installed
  package:
    name: python-pip
    state: present


- name: Ensure python-irodsclient is installed
  pip:
    name: git+https://github.com/irods/python-irodsclient.git
    editable: False
    state: present


- name: Ensure Yoda test users exists
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_mkuser:
    name: '{{ item.name }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have type
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'type'
    value: '{{ item.type }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have password
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'password'
    value: '{{ item.password }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test groups exists
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroup:
    groupName: '{{ item.groupName }}'
    category: '{{ item.category }}'
    subcategory: '{{ item.subcategory }}'
    description: 'Auto-generated by Ansible'
  with_items: '{{ test_groups }}'


- name: Ensure Yoda users are added to groups
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroupuser:
    groupName: '{{ item.groupName }}'
    user: '{{ item.user }}'
    role: '{{ item.role }}'
  with_items: '{{ test_groupusers }}'


- name: Ensure test data is available for iRODS
  become_user: '{{ irods_service_account }}'
  become: yes
  copy:
    src: '{{ item }}'
    dest: '~/test_data/{{ item }}'
  with_items:
    - 'yoda-metadata.xml'


- name: Ensure test data is in YoDa
  become_user: '{{ irods_service_account }}'
  become: yes
  command: 'iput -f ~/test_data/{{ item }} /{{ irods_zone }}/home/research-initial/'
  with_items:
    - 'yoda-metadata.xml'
