---
# copyright Utrecht University

- name: Ensure test users exists
  user:
    name: '{{ item.name }}'
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users exists
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_mkuser:
    name: '{{ item.name }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have type
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'type'
    value: '{{ item.type }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test users have password
  become_user: '{{ irods_service_account }}'
  become: yes
  irods_moduser:
    name: '{{ item.name }}'
    option: 'password'
    value: '{{ item.password }}'
  with_items: '{{ test_users }}'


- name: Ensure Yoda test groups exists
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroup:
    groupName: '{{ item.groupName }}'
    category: '{{ item.category }}'
    subcategory: '{{ item.subcategory }}'
    description: 'Auto-generated by Ansible'
  with_items: '{{ test_groups }}'


- name: Ensure Yoda users are added to groups
  become_user: '{{ irods_service_account }}'
  become: yes
  yoda_addgroupuser:
    groupName: '{{ item.groupName }}'
    user: '{{ item.user }}'
    role: '{{ item.role }}'
  with_items: '{{ test_groupusers }}'


- name: Ensure Yoda test data directory is present
  become_user: '{{ irods_service_account }}'
  become: yes
  file:
    path: '~/testdata/'
    state: directory
    mode: 0755


- name: Ensure Yoda test data directory is present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  shell:
    imkdir /{{ irods_zone }}/home/research-initial/testdata
  ignore_errors: true


- name: Ensure Yoda test files are present
  become_user: '{{ irods_service_account }}'
  become: yes
  copy:
    src: '{{ item }}'
    dest: '~/testdata/{{ item }}'
    mode: 0644
  with_items:
    - 'lorem.txt'
    - 'SIPI_Jelly_Beans_4.1.07.tiff'


- name: Ensure Yoda test files are present in Yoda
  become_user: '{{ irods_service_account }}'
  become: yes
  shell:
    iput -f ~/testdata/{{ item }} /{{ irods_zone }}/home/research-initial/testdata
  with_items:
    - 'lorem.txt'
    - 'SIPI_Jelly_Beans_4.1.07.tiff'
