---
# copyright Utrecht University

- name: Ensure PHP is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - php
  - php-xml
  - php-mcrypt
  notify: Restart Apache webserver


- name: Allow PHP to open TCP sockets in SELinux config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: Configure PHP in php.ini
  ini_file:
    path: /etc/php.ini
    section: Date
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0600
  with_items:
    - option: date.timezone
      value: '{{ timezone }}'
    - option: expose_php
      value: Off
    - option: max_execution_time
      value: 120
  notify: Restart Apache webserver
