---
# copyright Utrecht University

- name: Ensure PHP is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - php
  - php-xml
  - php-mcrypt
  notify: Restart Apache webserver


- name: Allow PHP to open TCP sockets in SELinux config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: Configure PHP timezone
  ini_file:
    path: /etc/php.ini
    section: Date
    option: date.timezone
    value: Europe/Amsterdam
    mode: 0600
  notify: Restart Apache webserver


- name: Configure the exposure of PHP version
  ini_file:
    path: /etc/php.ini
    section: PHP
    option: expose_php
    value: Off
    mode: 0600
  notify: Restart Apache webserver


- name: Configure the max execution time of PHP
  ini_file:
    path: /etc/php.ini
    section: PHP
    option: max_execution_time
    value: 120
    mode: 0600
  notify: Restart Apache webserver
