---
# ansible tasks within this role
# copyright Utrecht University

- name: Add EPEL repository for php-mcrypt
  yum:
    name='{{item}}'
    state=present
  with_items:
    - epel-release


- name: Ensure PHP is installed
  yum:
    name='{{item}}'
    state=present
  with_items:
  - php
  - php-xml
  - php-mcrypt
  - libsemanage-python
  - libselinux-python
  notify: Restart Apache webserver


- name: Allow PHP to open TCP sockets in SELinux config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes


- name: Set PHP timezone
  lineinfile:
    dest=/etc/php.ini
    create=no
    insertafter='^;date.timezone\s*=.*$'
    state=present
    line='date.timezone = Europe/Amsterdam'
    backup=yes


- name: Limit exposure of PHP version
  lineinfile:
     dest=/etc/php.ini
     create=no
     regexp='^expose_php\s*=.*$'
     state=present
     line='expose_php = Off'
     backup=no


- name: Extend max execution time of PHP
  lineinfile:
     dest=/etc/php.ini
     create=no
     regexp='^max_execution_time\s*=.*$'
     state=present
     line='max_execution_time = 120'
     backup=no