---
# copyright Utrecht University

- name: Add repository for PHP 7.2
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present


- name: Enable repository for PHP 7.2
  yum_repository:
    name: remi-php72
    description: Remi's PHP 7.2 RPM repository for Enterprise Linux 7
    mirrorlist: http://rpms.remirepo.net/enterprise/7/php72/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi


- name: Ensure PHP packages are installed
  package:
    name:
      - php
      - php-cli
      - php-xml
      - php-pecl-mcrypt
    state: latest
  when: not ansible_check_mode
  notify: Restart Apache webserver


- name: Allow PHP to open TCP sockets in SELinux config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux


- name: Ensure PHP is configured
  ini_file:
    path: /etc/php.ini
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0600
  with_items:
    - section: PHP
      option: expose_php
      value: Off
    - section: PHP
      option: max_execution_time
      value: 120
    - section: Date
      option: date.timezone
      value: '{{ timezone }}'
  notify: Restart Apache webserver
