---
# copyright Utrecht University

- name: Ensure PHP 5.4 is absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
  - php
  - php-cli
  - mod_php
  - php-common
  notify: Restart Apache webserver


- name: Add repository for PHP 7.2
  yum_repository:
    name: remi-php72
    description: Remi's PHP 7.2 RPM repository for Enterprise Linux 7
    mirrorlist: http://rpms.remirepo.net/enterprise/7/php72/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi


- name: Ensure PHP 7.2 is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
  - php72-php
  - php72-php-cli
  - php72-php-xml
  - php72-php-mcrypt
  notify: Restart Apache webserver


- name: Allow PHP to open TCP sockets in SELinux config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux


- name: Ensure PHP is configured
  ini_file:
    path: /etc/php.ini
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0600
  with_items:
    - section: PHP
      option: expose_php
      value: Off
    - section: PHP
      option: max_execution_time
      value: 120
    - section: Date
      option: date.timezone
      value: '{{ timezone }}'
  notify: Restart Apache webserver
