---
- name: SURFsara -- EUS -- Copying favicon
  copy:
    src: "../../{{ FAVICONPATH }}"
    dest: /var/www/extuser/yoda-external-user-service/public/static/img/favicon.ico
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Copying Header Img
  copy:
    src: "../../{{ HEADERIMG }}"
    dest: /var/www/extuser/yoda-external-user-service/public/static/img/headerimg
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Copy Yoda Portal header php
  template:
    src: "eus/start.phtml.j2"
    dest: "/var/www/extuser/yoda-external-user-service/views/common/start.phtml"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

#######
# These changes enable the EUS to send 
# mail based on local postfix servver
######

- name: SURFsara -- EUS -- Adjusting postfix main.cf for hostname
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^#myhostname = virtual.domain.tld"
    line: "myhostname = {{ ansible_host }}"
    state: present
    backrefs: true
  notify: Restart postfix

- name: SURFsara -- EUS -- Adjusting postfix main.cf for ipv4
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^inet_protocols = all"
    line: "inet_protocols = ipv4"
    state: present
    backrefs: true
  notify: Restart postfix

- name: SURFsara -- EUS -- Copy Yoda EUS PHP Mailer Template 
  template:
    src: "eus/mail.php.j2"
    dest: "/var/www/extuser/yoda-external-user-service/include/mail.php"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Syncing EUS templates
  copy:
    src: "files/eus/{{ eus_mail_template }}"
    dest: /var/www/extuser/yoda-external-user-service/mail-templates/
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Copy Yoda EUS Mail Template
  template:
    src: eus/activation-succesful.txt.j2
    dest: "/var/www/extuser/yoda-external-user-service/mail-templates/{{ eus_mail_template }}/activation-succesful.txt"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Copy Yoda EUS Success Template
  template:
    src: eus/activation-succesful.html.j2
    dest: "/var/www/extuser/yoda-external-user-service/mail-templates/{{ eus_mail_template }}/activation-succesful.html"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Template success page
  template:
    src: eus/activation-succesful.phtml.j2
    dest: "/var/www/extuser/yoda-external-user-service/views/activation-succesful.phtml"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- EUS -- Template password reset page
  template:
    src: eus/reset-password-succesful.phtml.j2
    dest: "/var/www/extuser/yoda-external-user-service/views/reset-password-succesful.phtml"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'


#- name: SURFsara -- EUS -- Creates a cron file under /etc/cron.d
#  cron:
#    name: eus dump
#    minute: "5"
#    hour: "*/6"
#    day: "*"
#    month: "*"
#    weekday: "*"
#    user: root
#    job: "sudo -i -u postgres 'pg_dumpall' > /root/eus.bak"
#    cron_file: cron_eus_dump

