---
- name: Include portals when portals
  include_tasks: portals.yml
  when: '"full-portal" in group_names'

- name: Include davrods when davrods
  include_tasks: davrods.yml
  when: '"full-davrods" in group_names'

- name: Include publics when publics
  include_tasks: publics.yml
  when: '"full-public" in group_names'

- name: Include eus when eus
  include_tasks: eus.yml
  when: '"full-eus" in group_names'
