---

- name: SURFsara -- PORTALS -- Creating targeted admin
  user:
    name: "{{ surfadmin }}"
    password: "{{ surfpass }}"
    shell: /bin/false
    create_home: no

- name: SURFsara -- PORTALS -- Copying favicon
  copy:
    src: "../../{{ FAVICONPATH }}"
    dest: /var/www/yoda/yoda-portal/public/static/img/favicon.ico
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- PORTALS -- Copying Header Img
  copy:
    src: "../../{{ HEADERIMG }}"
    dest: /var/www/yoda/yoda-portal/public/static/img/headerimg
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- PORTALS -- Copying Splash Img
  copy:
    src: "../../{{ SPLASHIMG }}"
    dest: /var/www/yoda/yoda-portal/public/static/img/splash
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'
  when: SPLASHIMG is defined
    
- name: SURFsara -- PORTALS -- Copy Yoda Portal splash page
  template:
    src: "portals/static_frontpage.html.j2"
    dest: "/var/www/yoda/yoda-portal/public/static/static_frontpage.html"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'
  when: SPLASHIMG is defined

- name: SURFsara -- PORTALS -- Copy Yoda Portal header php
  template:
    src: "portals/start.php.j2"
    dest: "/var/www/yoda/yoda-portal/views/common/start.php"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: SURFsara -- PORTALS -- Copy Yoda Portal login php
  template:
    src: "portals/login.php.j2"
    dest: "/var/www/yoda/yoda-portal/views/user/login.php"
    owner: "{{ yoda_deployment_user }}"
    group: "{{ yoda_deployment_user }}"
    mode: '0644'

- name: Ensure external user check is present
  copy:
    src: portals/is-user-external.sh
    dest: /usr/local/bin/is-user-external.sh
    owner: root
    group: {{ irods_service_account }}
    mode: 0750

- name: SURFsara -- PORTALS -- Adjusting uu.nl to be external users
  lineinfile:
    path: "{{ item }}"
    regexp: '^		if \(\*domain \!\= \"uu\.nl\" \&\& \*domain not like \"\*\.uu\.nl\"\) \{'
    line: '		if (*domain != "") {'
    state: present
    backrefs: true
  loop:
    - /etc/irods/rules-uu.re
    - /etc/irods/irods-ruleset-uu/rules-uu.re
    - /etc/irods/irods-ruleset-uu/uuGroup.r

- name: SURFsara -- PORTALS -- Adjusting storage statistics gathering cronjob
  become_user: "{{ irods_service_account }}"
  become: yes
  cron:
    name: 'monthly-storage-statistics'
    minute: 0
    hour: 0
    job: '/bin/irule -F /etc/irods/irods-ruleset-uu/tools/monthly-storage-statistics.r >> $HOME/log/job_monthly-storage-statistics.log 2>&1'

- name: SURFsara -- PORTALS -- Auto-include default license files
  become_user: "{{ irods_service_account }}"
  become: yes
  command: "iput -r /etc/irods/irods-ruleset-research/tools/licenses /{{ irods_zone }}/yoda"
  ignore_errors: true

#- name: Disabling asynchronous replication if set
#  become: yes
#  lineinfile:
#    path: "/etc/irods/rules-uu.re"
#    regexp: '^ *uuReplicateAsynchronously'
#    line: ' #disabled by SURFsara setup uuReplicateAsynchronously'
#    state: present
#    backrefs: true
