---
# copyright Utrecht University

rolename: irods-icat

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# iRODS iCAT rpm location and checksum
irods_icat:
  package: irods-icat-4.1.8
  url: ftp://ftp.renci.org/pub/irods/releases/4.1.8/centos7
  filename: irods-icat-4.1.8-centos7-x86_64.rpm
  checksum: sha256:ea4b0ec21d1ba186062382ea6ecdb25e9f9299434ddaad1086eb3cd8b22a8719

# iRODS database plugin rpm location and checksum
irods_db:
  package: irods-database-plugin-postgres-1.8
  url: ftp://ftp.renci.org/pub/irods/releases/4.1.8/centos7
  filename: irods-database-plugin-postgres-1.8-centos7-x86_64.rpm
  checksum: sha256:1d42fddaf243890aad03fb9da47cb259cd13cb0539a8fc81f3af0610d08b9c6d

# iRODS configuration.
irods_admin: rods
irods_password: rods
irods_database_fqdn: database.yoda.dev
irods_database_name: ICAT
irods_database_port: 5432
irods_database_user: irodsdb
irods_database_password: irodsdev
irods_authentication_scheme: Native        # "Native" or "Pam"
irods_zone: tempZone
irods_port_range_begin: 20000
irods_port_range_end: 20199
irods_icat_port: 1247
irods_service_account: irods
irods_vault_directory: /var/lib/irods/Vault
irods_control_plane_port: 1248
irods_schema_uri: https://schemas.irods.org/configuration

# PAM Radius configuration.
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

# OpenSSL configuration
openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'
openssl_dhparams: dhparams.pem
openssl_key_signed: localhost.key
openssl_crt_signed: localhost.crt