---
# copyright Utrecht University

- name: Find out if we need to install iRODS iCommands rpm
  stat: path='/etc/irods'
  register: irods_server


- name: Download iRODS iCommands rpm
  get_url:
    url='{{ irods_icommands.url }}/{{ irods_icommands.filename }}'
    dest='{{ rpm_dest_dir }}/{{ irods_icommands.filename }}'
    checksum='{{ irods_icommands.checksum }}'
  when: irods_server.stat.exists == false


- name: Ensure iRODS iCommands is installed
  package:
    name='{{ item }}'
    state=present
  with_items:
    - '{{ rpm_dest_dir }}/{{ irods_icommands.filename }}'
  when: irods_server.stat.exists == false