---
# copyright Utrecht University

- name: Find out if we need to install iRODS iCommands rpm
  stat:
    path: '/etc/irods'
  register: irods_server


- name: Ensure iRODS 4.1 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - irods-runtime-4.1.11-0
    - irods-icommands-4.1.11-0


- name: Ensure iRODS iCommands is installed
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - irods-icommands-4.2.2-1
  when: irods_server.stat.exists == false and not ansible_check_mode
