---
# copyright Utrecht University

- name: Find out if we need to install iRODS iCommands rpm
  stat: path='/etc/irods'
  register: irods_server


- name: Download iRODS iCommands rpm
  get_url:
    url='{{ irods_rpm_ftp }}/{{ irods_icommand_rpm }}'
    dest='{{ rpm_dest_dir }}/{{ irods_icommand_rpm }}'
    checksum='{{ irods_icommand_rpm_sha256 }}'
  when: irods_server.stat.exists == false


- name: Ensure iRODS iCommands is installed
  package:
    name='{{ item }}'
    state=present
  with_items:
    - '{{ rpm_dest_dir }}/{{ irods_icommand_rpm }}'
  when: irods_server.stat.exists == false