---
# copyright Utrecht University

- name: Find out if we need to install iRODS iCommands rpm
  stat:
    path: '/etc/irods'
  register: irods_server


- name: Ensure iRODS iCommands is installed
  yum:
    name: '{{ item }}'
    state: present
    skip_broken: yes
  with_items:
    - irods-icommands-4.2.1-1
  when: irods_server.stat.exists == false
