---
# copyright Utrecht University

- name: Find out if we need to install iRODS iCommands rpm
  stat:
    path: '/etc/irods'
  register: irods_server


- name: Ensure iRODS 4.1 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - irods-runtime-4.1.11-0
    - irods-icommands-4.1.11-0


- name: Ensure iRODS 4.2.2 packages are absent
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - davrods-4.2.2_1.4.0-1
    - irods-sudo-microservices-4.2.2_1.0.0-1
    - irods-uu-microservices-4.2.2_0.7.5-1


- name: Ensure iRODS iCommands is installed
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - irods-icommands-4.2.3-1
  when: irods_server.stat.exists == false and not ansible_check_mode
