---
# copyright Utrecht University

- name: Ensure Yoda landingpages root is world readable
  file:
    path: '{{ landingpages_root }}'
    mode: 0755
    owner: '{{ yoda_inbox_user }}'
    group: 'apache'
    state: directory


- name: Ensure inbox user exists
  user:
    name: '{{ yoda_inbox_user }}'


- name: Add upload user pub key to authorized_keys of inbox
  authorized_key:
    user: '{{ yoda_inbox_user }}'
    key: '{{ upload_pub_key | b64decode }}'
    state: present


- name: Check if index page is present
  stat: path='{{ landingpages_root }}/index.html'
  register: index


- name: Ensure empty index page is present
  file:
    path: '{{ landingpages_root }}/index.html'
    state: touch
  when: index.stat.exists == False


- name: Ensure old Yoda landingpages Apache configuration is absent
  file:
    path: /etc/httpd/conf.d/landingpages-vhost.conf
    state: absent


- name: Ensure Yoda landingpage static file directories are present
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ landingpages_root }}/static/css/'
    - '{{ landingpages_root }}/static/img/'


- name: Ensure Yoda landingpage static files are present
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
  with_items:
    - src: 'yoda-landingpage.css'
      dest: '{{ landingpages_root }}/static/css/yoda-landingpage.css'
    - src: 'logo-uu.png'
      dest: '{{ landingpages_root }}/static/img/logo-uu.svg'
    - src: 'logo_footer.svg'
      dest: '{{ landingpages_root }}/static/img/logo_footer.svg'
