---
# copyright Utrecht University

- name: Ensure Yoda landingpages root is world readable
  file:
    path: '{{ landingpages_root }}'
    mode: 0755
    owner: '{{ yoda_inbox_user }}'
    group: 'apache'
    state: directory


- name: Ensure inbox user exists
  user:
    name: '{{ yoda_inbox_user }}'


- name: Add upload user pub key to authorized_keys of inbox
  authorized_key:
    user: '{{ yoda_inbox_user }}'
    key: '{{ upload_pub_key | b64decode }}'
    state: present


- name: Ensure empty index page is present
  file:
    path: '{{ landingpages_root }}/index.html'
    state: touch


- name: Ensure old  Yoda landingpages Apache configuration is absent
  file:
    path: /etc/httpd/conf.d/landingpages-vhost.conf
    state: absent
