---
# copyright Utrecht University

# YoDa configuration.
yoda_version: development

# iRODS configuration.
irods_admin: irods
irods_password: rods
irods_database_name: ICAT
irods_database_user: irodsdb
irods_database_password: irodsdev
irods_zone: tempZone
irods_icat_fqdn: icat.yoda.dev
irods_database_fqdn: database.yoda.dev
irods_resources:
  - name: dev001_1
    host: icat.yoda.dev
    vault_path: /var/lib/irods/iRODS/dev001_1/Vault
    resource_type: unixfilesystem

  - name: dev001_2
    resource_type: unixfilesystem
    host: icat.yoda.dev
    vault_path: /var/lib/irods/iRODS/dev001_2/Vault

  - name: dev001_p1
    resource_type: passthru
    children:
      - dev001_1

  - name: dev001_p2
    resource_type: passthru
    children:
      - dev001_2

  - name: dev001
    resource_type: random
    children:
      - dev001_p1
      - dev001_p2

  - name: irodsResc
    resource_type: random
    children:
      - dev001

  - name: dev002_1
    resource_type: unixfilesystem
    host: resource.yoda.dev
    vault_path: /var/lib/irods/iRODS/dev001_1/Vault 

  - name: dev002_p1
    resource_type: passthru
    children:
      - dev002_1

  - name: dev002
    resource_type: random
    children:
      - dev002_p1

  - name: irodsRescRepl
    resource_type: random
    children:
      - dev002
