---
# copyright Utrecht University

########################
# Ansible configuration
########################
ansible_user: vagrant                             # Administrative user on instance for Ansible
ansible_ssh_private_key_file: vagrant/ssh/vagrant # Private key file of administrative user

#####################
# YoDa configuration
#####################
instance: allinone                         # Name of Yoda instance, as defined in hosts
yoda_version: development                  # Git branch
codeigniter_environment: development       # CodeIgniter environment: development, testing, acceptance or production
yoda_portal_fqdn: portal.yoda.dev          # Yoda Portal fully qualified domain name (FQDN)
yoda_davrods_fqdn: data.yoda.dev           # Yoda Davrods WebDAV fully qualified domain name (FQDN)

######################
# iRODS configuration
######################
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_database_user: irodsdb               # The iRODS database username
irods_database_password: irodsdev          # The password for the iRODS database username
irods_authentication_scheme: Native        # iRODS authentication method: "Native" or "PAM"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_icat_fqdn: combined.yoda.dev         # iRODS iCAT fully qualified domain name (FQDN)
irods_database_fqdn: combined.yoda.dev     # iRODS database fully qualified domain name (FQDN)
irods_resource_fqdn: combined.yoda.dev     # iRODS resource fully qualified domain name (FQDN)
irods_default_resc: irodsResc              # iRODS default resource name
irods_resources:
  - name: dev001_1
    host: "{{ irods_icat_fqdn }}"
    vault_path: /var/lib/irods/Vault1_1
    resource_type: unixfilesystem

  - name: dev001_2
    resource_type: unixfilesystem
    host: "{{ irods_icat_fqdn }}"
    vault_path: /var/lib/irods/Vault1_2

  - name: dev001_p1
    resource_type: passthru
    children:
      - dev001_1

  - name: dev001_p2
    resource_type: passthru
    children:
      - dev001_2

  - name: dev001
    resource_type: random
    children:
      - dev001_p1
      - dev001_p2

  - name: irodsResc
    resource_type: random
    children:
      - dev001

  - name: dev002_1
    resource_type: unixfilesystem
    host: "{{ irods_resource_fqdn }}"
    vault_path: /var/lib/irods/Vault2_1

  - name: dev002_p1
    resource_type: passthru
    children:
      - dev002_1

  - name: dev002
    resource_type: random
    children:
      - dev002_p1

  - name: irodsRescRepl
    resource_type: random
    children:
      - dev002

########################
# Ruleset configuration
########################
rulesets:
  - name: irods-ruleset-i-lab
    repo: https://github.com/UtrechtUniversity/irods-ruleset-i-lab.git
    ruleset_name: rules-i-lab
    version: "{{ yoda_version }}"
    install_scripts: no
  - name: irods-ruleset-research
    repo: https://github.com/UtrechtUniversity/irods-ruleset-research.git
    ruleset_name: rules-research
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: irods-ruleset-uu
    repo: https://github.com/UtrechtUniversity/irods-ruleset-uu.git
    ruleset_name: rules-uu
    version: "{{ yoda_version }}"
    install_scripts: yes
  - name: core
    ruleset_name: core
    path: /etc/irods/core.re
    install_scripts: no

################################
# Research module configuration
################################
default_yoda_schema: ilab    # Default Yoda XML scheme: ilab or dc
enable_revisions: 1          # Enable revisions: yes (1) or no (0)
revision_strategy: B         # Revision strategy: A, B, J or Simple

###########################
# PAM Radius configuration
###########################
# server, shared secret, timeout (s)
pam_radius_config: |
  127.0.0.1     secret         1
  other-server  other-secret   3

##########################
# MOAI configuration
##########################
yoda_moai_fqdn: moai.yoda.dev
yoda_moai_port: 80

###########################
# Public host configuration
###########################
yoda_public_host: combined.yoda.dev
